### ISSUE TITLE
Scale bar on the map

### ISSUE THREAD

**Issue by SimonKnorke** [thedirtyfew/dash-leaflet#10]
Hi, 

I wonder how I can create a scale bar on the map to get a visual indication of the distances between the markers. I'm referring to the post

https://gis.stackexchange.com/questions/54644/leaflet-show-miles-kilometers .

I couldn't find a corresponding feature in react-leaflet. 

Is there a (quick and dirty) solution for such a scale bar?

**Comment by emilhe** [comment]
I have just (0.0.9) added a ScaleControl. Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl

app = dash.Dash()
app.layout = html.Div([dl.Map([dl.TileLayer(), dl.ScaleControl()])], style={'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server()
```

**Comment by SimonKnorke** [comment]
Awesome, thanks!
