### ISSUE TITLE
clickStyle as like hoverStyle [new feature]

### ISSUE THREAD

**Issue by heidler** [thedirtyfew/dash-leaflet#101]
Hey guys, I tried to change color of polyline on click, but I don't know how. I know there is component click_feature, but I don't know how to force change of color on clicked feature.

**So I think it would be awesome if we could have something similiar like hoverStyle. Then it would be easy to change style on click.**

Btw if you could tell me how to change the style of clicked feature, I would be really glad. ^^ link to [stack-overflow](https://stackoverflow.com/questions/68427622/dash-leaflet-geojson-change-color-of-last-clicked-feature).

**Comment by prl900** [comment]
I think you can do what you want passing the `style` options as a dictionary to the GeoJSON object. The general styling for displaying polygons can be defined using the `options` prop or you can also pass a different style to the `hoverStyle` prop. 

See the following example from one of my applications:

```
geojson = dl.GeoJSON(id="geojson",
                     data=data,
                     zoomToBoundsOnClick=True,  # when true, zooms to bounds of feature (e.g. cluster) on click
                     options=dict(style=dict(weight=2, opacity=1, fillOpacity=0.1)),
                     hoverStyle=arrow_function(dict(weight=5, color='#666', fillOpacity=0.5, dashArray='')))
```

I agree the way of doing this is not the most intuitive but I hope it helps you move forward.

**Comment by heidler** [comment]
OK, but I'm not sure how to do it. I wanted to do something like that:
```
app.clientside_callback(
    """function(feature){
        // set and return color
        ;}""",
    Output("geojson", ???), # To what children?
    Input("geojson", "click_feature")
    )
```

When user clicks on feature (polyline) I want change the color of clicked feature (polyline 1), when he clicks on another feature (polyline 2) I want to change that color and get polyline 1 color to default state.

**Comment by prl900** [comment]
Sorry @heidler I misread your question. I don't know either how to change the styling of just the clicked polyline.

**Comment by heidler** [comment]
> Sorry @heidler I misread your question. I don't know either how to change the styling of just the clicked polyline.

np @prl900 , let's see if anyone can help us out! :)

**Comment by emilhe** [comment]
@heidler I have posted an example on SO. Let me know if it works out :)

https://stackoverflow.com/questions/68427622/dash-leaflet-geojson-change-color-of-last-clicked-feature

**Comment by heidler** [comment]
> @heidler I have posted an example on SO. Let me know if it works out :)
> 
> https://stackoverflow.com/questions/68427622/dash-leaflet-geojson-change-color-of-last-clicked-feature

Awesome, thank you! But still, maybe you can implement this feature! :)

**Comment by heidler** [comment]
@emilhe I have one more question regards z-index on clicked feature. Can you pls elaborate in stack-overlow?

> I have one more question, right know the hover implementation is that, what feature you hover last on, it will have the highest z-index. But I want to have the clicked feature to be with the highest z-index, so the feature ​will not be under the other features. I tried to do it with adding className and via CSS z-index property. But it doesn't work.

**Comment by emilhe** [comment]
I would suggest creating a separate GeoJSON component for the clicked feature. Wrapping this "clicked-feature-geojson" component in a Pane component, you can control the z-index via CSS.
