### ISSUE TITLE
More control of EditControl?

### ISSUE THREAD

**Issue by Folgrim** [thedirtyfew/dash-leaflet#103]
First off thanks for adding EditControl.  Great stuff!

However I am struggling to use it a bit.  Like the example hosted in heroku, I like the concept of converting drawn objects to fully-fledged dash-leaflet objects that I have more control over and can more easily access, however in my case it would be on the same map.  So I want to draw a rectangle or polygon, then immediately convert it (as the example does), and delete the drawn polygon via callback, keeping only the converted one.  However I can't seem to find a way to delete EditControl-drawn polygons via callback (the only way I can is by manually using the buttons).

Emptying the geojson data for EditControl via callback doesn't remove the drawn objects.  There is no way that I can tell to trigger a deletion via callback.  Recreating the EditControl via callback doesn't help (wipes the geojsons but not the objects on the map).  I tried to figure out what featuregroup the objects were being drawn to and even tried setting my own featuregroup via the edit[featuregroup] option but that likewise didn't work.

Would it be possible to have EditControl mirror the geojson both ways, so we can both read drawn objects (as we can now) and write them by editing the geojson via callback?  Another option, for my specific use-case anyway, would be a callback that just wipes everything that has been drawn.  Or lastly, maybe we could set the featuregroup that EditControl is using to one that dash-leaflet can manipulate?  

Thanks Emil!

**Comment by prl900** [comment]
Yes, I agree that having access to the EditControl functionality outside the map would be very useful.

I know @emilhe has had a look at this and apparently it's not that straightforward to implement. However, it would be great if we can use this issue to discuss and understand what is required to come up with a generic wrapper for exposing the EditControl functionality (and other Leaflet map controls) as callbacks in Dash.

**Comment by emilhe** [comment]
I really like the idea of a two-way binding. However, as @prl900 notes, the implementation of the underlying leaflet component wasn't really designed for it. I already had to add a decent amount of code on top to expose the drawn geometries (the "read" part) as a Dash prop. To achieve a proper two-way binding, I believe it might be easier to implement a new leaflet control from scratch.

**Comment by ougx** [comment]
Is it possible to manually add feature to `EditControl` and display those features?

I was able to change `EditControl.geojson['features']` but the added features are not shown on the map.

Thanks!

**Comment by emilhe** [comment]
@ougx No, with the current implementation that is not possible. The binding is only one way, from the control to Dash, not the other way.

**Comment by ougx** [comment]
Thanks, @emilhe. I can add features to the `featureGroup` manually that I can edit and remove those features using `EditControl`.  The feature will disappear from the map when removed. However, they are still in the `featureGroup`. Do you know any property has changed to those removed features to make them disappear from the map? I am trying to identify the removed features and remove them manually from `featureGroup`.

```python
import dash_html_components as html
import dash_leaflet as dl
from dash import Dash
from dash.dependencies import Output, Input, State
from dash.exceptions import PreventUpdate
from dash import callback_context as ctx


app = Dash()
app.layout = html.Div([
    # Setup a map with the edit control.
    html.Div(html.Button('Add', id='add')),
    html.Div(html.Button('Remove', id='remove')),
    html.Div(html.Button('Print', id='print')),
    dl.Map(center=[41, -98], zoom=8.5, children=[
        dl.TileLayer(), dl.FeatureGroup([
            dl.EditControl(
                id="edit_control",
                draw=dict(circle=False, retangle=False, circlemarker=False),
            ), ], id='fg'),
    ], style={'width': '1000px', 'height': '500px'}, id="map"),
    html.Div('Zone: ', id='ffg',)
])


@app.callback(Output("ffg", "children"), Input("print", "n_clicks"), State('fg', 'children'))
def print_fg(nclick, fgroup):
    print(nclick, fgroup)
    if nclick:
        return str(fgroup)
    return ''


@app.callback(Output('fg', 'children'), Input("add", "n_clicks"), Input("remove", "n_clicks"), State('fg', 'children'))
def click(add, remove, fgroup):

    if not ctx.triggered:
        button_id = 'No clicks yet'
    else:
        button_id = ctx.triggered[0]['prop_id'].split('.')[0]

    if button_id=='add':
        fgroup.append(dl.Marker(position=(41+add/10, -98+add/10), id={'type': 'new', 'index':add}))
        return fgroup

    if button_id=='remove':
        if len(fgroup)>1:
            fgroup = fgroup[:-1]
            return fgroup

    raise PreventUpdate


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by emilhe** [comment]
From `dash-leaflet==0.1.18` it is now possible to invoke the events, which are dispatched by buttons clicks. Hence you can now move all of the UI to Dash buttons if you like. Here is a small example,

```
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input
from dash_extensions.enrich import DashProxy, MultiplexerTransform

# Mode definitions.
draw_modes = ["marker", "polygon", "polyline", "rectangle", "circle", "circlemarker"]
edit_modes = ["edit", "remove"]
# Create example app.
app = DashProxy(transforms=[MultiplexerTransform()], prevent_initial_callbacks=True)
app.layout = html.Div(
    [
        dl.Map(center=[56, 10], zoom=4, children=[
            dl.TileLayer(), dl.FeatureGroup([
                dl.EditControl(id="edit_control"),
                dl.Marker(position=[56, 10])]),
        ], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "inline-block"},
               id="map")
    ] +
    # Mode buttons.
    [html.Div("Draw")] +
    [html.Button(mode, id=mode) for mode in draw_modes] +
    [html.Div("Edit")] +
    [html.Button(mode, id=mode) for mode in edit_modes] +
    # Action buttons.
    [
        html.Div("Actions"),
        html.Button("polygon -> delete last point", id="poly_delete"),
        html.Button("polygon -> finish", id="poly_finish"),
        html.Button("remove -> clear all", id="clear_all")
    ])
# Create draw mode callbacks.
for mode in draw_modes:
    app.callback(Output("edit_control", "drawToolbar"), Input(mode, "n_clicks"))(
        lambda n_clicks, m=mode: dict(mode=m, n_clicks=n_clicks))
# Create edit mode callbacks.
for mode in edit_modes:
    app.callback(Output("edit_control", "editToolbar"), Input(mode, "n_clicks"))(
        lambda n_clicks, m=mode: dict(mode=m, n_clicks=n_clicks))
# Create a few action callbacks, but not all - there are too many combinations...
app.callback(Output("edit_control", "drawToolbar"), Input("poly_delete", "n_clicks"))(
    lambda n_clicks: dict(mode="polygon", n_clicks=n_clicks, action="delete last point"))
app.callback(Output("edit_control", "drawToolbar"), Input("poly_finish", "n_clicks"))(
    lambda n_clicks: dict(mode="polygon", n_clicks=n_clicks, action="finish"))
app.callback(Output("edit_control", "editToolbar"), Input("clear_all", "n_clicks"))(
    lambda n_clicks: dict(mode="remove", n_clicks=n_clicks, action="clear all"))

if __name__ == '__main__':
    app.run_server(port=7781, debug=True)
```

**Comment by Folgrim** [comment]
This is great @emilhe.  Thank you!  It really helped enable my use-case.  

My only minor complaint would be that it seems the "remove" button must actually exist in order to trigger it's action via callback, which makes sense I suppose.  In my specific use-case, I don't have a need for it, so I just hid it via css.

Thanks again.

**Comment by emilhe** [comment]
@Folgrim that nice to hear! And, yes, if you "remove button" via the component itself, the underlying functionality it disabled too (that is a (reasonable) design choice by the author of the underlying leaflet component). As you already figured out, I would recommend hiding the buttons via CSS if you don't need them :)

**Comment by galgerman** [comment]
thanks for the library its amazing,
could you maybe add a simple example of how could you remove a specific polygon for example? i need a way to emulate a way to click on remove the choose 1 polygon to remove instead of clear all,

thanks in advance!
