### ISSUE TITLE
Mouse-Over in the GeoJSON component messes up SVG drawing order of leaflet pane

### ISSUE THREAD

**Issue by matthiak** [thedirtyfew/dash-leaflet#104]
Problem: When mixing GeoJSON and Polyline components using different Layergroups doesn't create actual groups in the rendered SVG. All elements are put into a single SVG group and the drawing order of SVG defines what's drawn on top of another. The drawing order changes if elements are changed (style). 

Expected Behaviour: Children of defined Layergroups should appear in actual groups in the SVG document, keeping the defined order of drawing.

Details:
I have a problem when using the geojson layer and a polyline layer in dash, when I use the mouse-over callback in the geojson component. 
I create a map with a tilelayer and two more layers to show a choropleth map and another layer to show additional information in form of polylines

```
dl.Map(	id="map", center=[39, -98], zoom=4,
	children=[
		dl.LayersControl([
			dl.BaseLayer(dl.TileLayer(), name="Base", checked=True),
			dl.Overlay(dl.LayerGroup(id="geojson"), name="one", checked=True),
			dl.Overlay(dl.LayerGroup(id="polyline"), name="two", checked=True)
		])
	],
	style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})
```

The content of the layer groups is added during a dash callback function, where i create the choropleth map and the polylines.
The Output fields from the callback function are for id "geojson" and id "polyline"

```
@app.callback(
	# to update the map we update the 'children' attribute
	Output("geojson", "children"),
	Output("polyline", "children"),
	...
def cb(..):
	...
	layer_geojson = dl.GeoJSON(	url="assets/US-states-geojson.json",  # url to geojson file
		options=dict(style=Solution_Vis_Leaflet.style_geojson_handle),  # how to style each polygon
		zoomToBounds=False,  # when true, zooms to bounds when data changes (e.g. on load)
		zoomToBoundsOnClick=True,  # when true, zooms to bounds of feature (e.g. polygon) on click
		hideout=dict(
			data=data
			colors=self.colors,
			style=javascript_style_function),
		hoverStyle=arrow_function(dict(weight=5, color='#666', dashArray='')),  # style applied on hover

	)
	polyline_array = [ARRAY OF POLYLINES]
	
	return layer_geojson, polyline_array
```

When I return the elements from this callback it renders them in correct order. Choropleth first and the polylines on top. I checked the SVG in the leaflet-overlay-pane in the browser and it seems ok.
The issue is when the mouse over function is triggered (defined in hoverStyle) in that the geojson polygon (where the mouse over happened) is removed from the SVG group and re-added with the mouse-over style at the end of the SVG document. Now the choropleth polygon is drawn on top of the polyline.

**Comment by emilhe** [comment]
Have you tried playing with the `Pane` component? As I remember, all SVG element are drawn to the same pane per default, by you can customize that via the `Pane` component.

**Comment by matthiak** [comment]
Hi,
thanks for your quick reply.
I tried the pane component and it solved my issue. 
Is the any control to add SVG elements to groups, as defined in the python code using Layergroup components?

**Comment by emilhe** [comment]
@matthiak Great! I am not sure what you mean by (1), could you elaborate? About (2), did you try changing the `options` prop (which holds the style information) of the GeoJSON?

**Comment by matthiak** [comment]
I'll try to explain better
To 1) 
I'll abstract the problem I ran into.

When I create a leaflet map like so:
```python
dl.Map( id="map", children=[ dl.TileLayer(), dl.LayerGroup(id="A") ,dl.LayerGroup(id="B") ] )
```
and I have a callback function that adds elements to the children of those layergroups
```python
@app.callback(
    Output("A", "children"),
    Output("B", "children"),
    Input("mydata", "data")
def cb(data):
    # polylines are created based on the data..
    poly1 = dl.Polyline( positions=posarray1, color="#fff" )
    poly2 = dl.Polyline( positions=posarray2, color="#fff" )
    return poly1, poly2
```
Should the rendered SVG then reflect the structure created in the python code (2 groups and one polyline per group) like so?
```html
<div> <!-- Overlay Pane -->
  <svg>
   <g><!-- svg group for Layergroup id="A"-->
    <path><!-- svg path for Polyline 'poly1 --> </path>
   </g>
   <g><!-- svg group for Layergroup id="B"-->
    <path><!-- svg path for Polyline 'poly2 --> </path>
   </g>
  </svg>
</div>
```
Or is the currently resulting SVG (all polylines from all layergroups in one SVG group):
```html
<div> <!-- Overlay Pane -->
  <svg>
   <g><!-- just one svg group for all Layergroups -->
    <path><!-- svg path for Polyline 'poly1 --> </path>
    <path><!-- svg path for Polyline 'poly2 --> </path>
   </g>
  </svg>
</div>
```

a limitation of the underlying leaflet library?

To 2. 
I am using the `options` parameter in the `dl.GeoJSON` component to set the color of the choropleth map items. But I also use the `hoverStyle` parameter, which I took directly from your example on the website `hoverStyle=arrow_function(dict(weight=5, color='#666', dashArray=''))`

As soon as the hover function is triggered by the mouse over, it removes the `path` element from the SVG group and adds it back to the end of the group with the mouse-over style. The same happens during mouse-out. The element is removed and added back to the SVG document. You can see it happening as well in your Choropleth map example on your website.

My question is: Wouldn't it be more effective to leave the `path` element in the SVG document and just change the element's attributes as returned by the array_function? Leaving it in place would also result in a stable order of elements and a stable drawing order.

Cheers.

**Comment by emilhe** [comment]
1) The dash-leaflet library only implements bindings from Dash to react-leaflet, the resulting object structure (which you are asking about) is controlled by the underlying library (as you suggest), i.e. react-leaflet (or leaflet itself). 

2) This behavior is also implemented in react-leaflet (or leaflet itself). I am not sure why this design was chosen, but I don't imagine that the performance impact is significant. Did you do any profiling?

**Comment by emilhe** [comment]
As a side note, you can control layer structure via the `Pane` component if needed :)

**Comment by matthiak** [comment]
Thanks for the explanations.
I suspected that you are limited by the react-leaflet component and probably leaflet itself. I have not used leaflet for such kind of things before.
In the end I solved this issue by using multiple panes, each pane shows a different visual class of SVG graphics.

Cheers :)

This issue can be closed
