### ISSUE TITLE
Using LayersControl sends WMSTileLayer to the background

### ISSUE THREAD

**Issue by prl900** [thedirtyfew/dash-leaflet#105]
I'm seeing some unexpected behaviour when mixing in an app LayersControl and a WMSTileLayer represented on top. Whenever a layer gets selected from the LayerControl the WMSTileLayer rendered on top of the baselayers gets send to the background, so it cannot be seen. I think this is a bug but it might also be that I'm not doing things correctly.

Here is a simple code to reproduce this behaviour:
```
import os
import dash
import dash_html_components as html
import dash_leaflet as dl

app = dash.Dash()

app.layout = html.Div([
                dl.Map(children=[
                    dl.LayersControl([
                        dl.BaseLayer(dl.TileLayer(url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"), name="satellite", checked=True),
                        dl.BaseLayer(dl.TileLayer(), name="map", checked=False),
                    ], position='bottomleft'),
                    dl.WMSTileLayer(url="https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
                                    layers="nexrad-n0r-900913", format="image/png", transparent=True),
                    ], center=(40,-100), zoom=4, style={'height': '99vh'}),
            ])

if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=int(os.environ.get("PORT", 8080)), debug=True, use_reloader=False)
```

The WMS layer can be seen at the start but once the base layer is changed it disappears from view. The WMS can be momentarily seen when flicking in between the base layers so it seems to be there sitting in the background.

Thanks

**Comment by emilhe** [comment]
It believe it is because all the tile based layers are drawn to the same pane per default. If you put the `WMSTileLayer` in its own pane, the problem should be solved,

import os
import dash
import dash_html_components as html
import dash_leaflet as dl

app = dash.Dash()

app.layout = html.Div([
    dl.Map(children=[
        dl.LayersControl([
            dl.BaseLayer(dl.TileLayer(
                url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"),
                         name="satellite", checked=True),
            dl.BaseLayer(dl.TileLayer(), name="map", checked=False),
        ], position='bottomleft'),
        dl.Pane(dl.WMSTileLayer(url="https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
                                layers="nexrad-n0r-900913", format="image/png", transparent=True))
    ], center=(40, -100), zoom=4, style={'height': '99vh'}),
])

if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=int(os.environ.get("PORT", 8080)), debug=True, use_reloader=False)

**Comment by prl900** [comment]
This works perfectly, thank you very much for your help @emilhe. I didn't realise `dl.Pane` can be used to define new and independent map layers in Leaflet. I will use this in the future, it's a very useful functionality.
