### ISSUE TITLE
Add hover and click events to leaflet map elements

### ISSUE THREAD

**Issue by matthiak** [thedirtyfew/dash-leaflet#107]
Hi,
according to the dash leaflet documentation the only events (to my knowledge) that are currently supported are
* click_lat_lng: where you get the lat lon coordinates of the clicked point on the map
* click_feature: where you can get the feature from a geojson data structure

What I'm missing are optional hover and click events for all elements placed on the map, where elements could be part of UI layers or Vector layers. The react leaflet documentation shows that such elements have an `eventHandlers` property where mouse events can be added.

Would it be possible to add an attribute to the dash leaflet components, like circle, polygon, line, marker, etc., that take a list of requested mouse events, such as 'click', 'hover', and then the dash callback would return the type of event (click or hover) and a) the reference to the element, if client-side callback, or b) the ID of this component, if server-side callback.

**Comment by emilhe** [comment]
You can see what events have been mapped from the docs strings, when are generated based on the proptype definitions. For the `Map` component itself, the following properties represent events

```
    /**
     * Dash callback property. Receives [lat, lng] upon click.
     */
    click_lat_lng: PropTypes.arrayOf(PropTypes.number),

    /**
     * Dash callback property. Receives [lat, lng] upon double click.
     */
    dbl_click_lat_lng: PropTypes.arrayOf(PropTypes.number),

    /**
     * Dash callback property. Receives [lat, lng, accuracy] when user location is found.
     */
    location_lat_lon_acc: PropTypes.arrayOf(PropTypes.number)
```

In addition to these events, some component have properties that expose events related to the component itself. The `Circle`, `Polygon`, `PolyLine`, and `Marker` components that you mention all support click events already. 

If you would like to monitor multiple components via a single callback, I would suggest using the `GeoJSON` component instead. In addition to click events, it  exposes the feature clicked as well as the feature hovered,

```
    /**
     * Dash callback property. Number of times the object has been clicked.
     */
    n_clicks: PropTypes.number,

    /**
     * Last feature clicked.
     */
    click_feature: PropTypes.object,

    /**
     * Last feature hovered.
     */
    hover_feature: PropTypes.object,
```

**Comment by matthiak** [comment]
Thanks for your feedback.
I have two questions:
1) Is there a reason why only the `Circle` component has the `n_clicks` property and the others only the `click_lat_lng` and `dbl_click_lat_lng` properties?

2) Since I don't know how many Circle and Polyline elements I have on my map upfront I could use the GeoJSON component, according to your suggestion, but then I have to manually create circles, which is certainly possible.

Not going down the GeoJSON path would mean I have to create either n callbacks dynamically, or a single callback with an Input array of size _n_, like: `[Input(str(i), "click_lat_lng") for i in range(n)]`. But I don't know _n_ upfront.

Now to my question:
The dash library supports Pattern-Matching Callbacks. But the examples only talk about dropdown components.
Would it be an idea to add support for Pattern-Matching Callbacks to leaflet components, to have one callback for a-priori unknown map components and return a specific value from the map component?

**Comment by emilhe** [comment]
Pattern matching callbacks are supported. I didn't use them in examples to avoid unnecessary complicity. However, the GeoJSON component will yield better performance, especially if you have many features.
