### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by garikhgh** [thedirtyfew/dash-leaflet#11]
Hi, thanks for awesome package.
I have several questions.
1) is it possible to get the marker label in callbacks not the coordinates?
2) is it possible to change the colour of rectangle when hovering, and when the rectangle is clicked.
 3) is it possible to create an area like html area, and do the point 2). ?

**Comment by emilhe** [comment]
Thanks!

1) If you attach the callback to the `Marker` object, rather than the map itself, your can get the marker id via the Dash callback context. Would that suffice?
2) Currently, Rectangles support click events. Hence, to change the color on click, you could attach a callback that changes the color (or redraws the rectangle if needed) on clik. Hoover events are not support at the moment.
3) I am not sure what you mean, could you elaborate? You should be able to create all kinds of shapes via `Polygon` object.

\emher

**Comment by garikhgh** [comment]
thanks for your feedback. the 3rd point is clear.
but it is not clear what 'component_property' to pass to the callback to get the marker id,
and could we get the polygon id with the callback?

My problem is the following, I have several polygons, and I want to get the polygon id in one callback in order to some calculations. the same I want to do with the markers.

could you please give some toy example?

thanks beforehand.

**Comment by emilhe** [comment]
You can always get the id of the object which triggered the callback. You can either use the dash `callback_context` object directly or the `get_trigger` from my util package. Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Input, Output
from dash_extensions.callback import get_trigger

app = dash.Dash()
app.layout = html.Div([dl.Map([dl.TileLayer(),
                               dl.Marker(position=[56, 10], id="marker"),
                               dl.Rectangle(bounds=[[57, 11], [58, 12]], id="rectangle")]),
                       html.Div(id="message")], style={'width': '1000px', 'height': '500px'})


@app.callback(Output("message", "children"),
              [Input("marker", "n_clicks"), Input("rectangle", "click_lat_lng")])
def who_clicked(n_clicks, click_lat_lng):
    trigger = get_trigger()
    return "You clicked the {}".format(trigger.id)


if __name__ == '__main__':
    app.run_server()

```

**Comment by garikhgh** [comment]
Thanks, it worked.

**Comment by garikhgh** [comment]
in usage_example.py, you use import settings, what package is it?

**Comment by emilhe** [comment]
It is just a file that contains my mapbox token (which is not checked in, as tokens are not to be shared). It you prefer to enter the token directly, you can just delete the import statement and replace

`mapbox_token = settings.MAPBOX_TOKEN`

by

`mapbox_token = YOUR_MAPBOX_TOKEN_HERE`

**Comment by garikhgh** [comment]
one more time thanks for awesome package
