### ISSUE TITLE
How to use PolylineDecorator with GEOJson

### ISSUE THREAD

**Issue by ReichYang** [thedirtyfew/dash-leaflet#113]
Hi. I wonder if there is a way to apply different polyline decorators to my geojson polygons based on the properties?

**Comment by emilhe** [comment]
It might be possible to creating an appropriate rendering function and passing it to via the `style ` entry of the `options` prop. See the documentation for inspiration,

http://dash-leaflet.herokuapp.com/#choropleth_us
