### ISSUE TITLE
Draw Freehand Polygons

### ISSUE THREAD

**Issue by Robbie-Palmer** [thedirtyfew/dash-leaflet#118]
I would like to enable a user to draw Freehand Polygons
The use case being wanting to draw a detailed polygon, simply by clicking and holding the mouse click button and tracing the region vs currently requiring to click along fine edges

The user interaction flows like:
1. Click and hold mouse button where Polygon should start
2. Drag mouse while holding, into shape of Polygon exterior
3. Let go of mouse button to have polygon auto-complete / close
    - Validation of whether or not this is a valid polygon can be handled by front-end or back-end? E.g. handle overlapping segments 

An example of this functionality can be tried [on this plotly image example](https://plotly.com/python/images/#annotating-layout-image-with-shapes)
The tooling here includes: line, open freeform, closed freeform, cicle and rectangle
Closed freeform is the functionality I'm looking for
A related example is [plotly's lasso selection](https://plotly.com/javascript/lasso-selection/) which allows freeform polygons to be drawn
If this action could be taken by a user and the corresponding geoJson sent to a callback, then the callback could publish a corresponding annotation, or conduct geospatial queries, opening up many use cases

**Comment by Robbie-Palmer** [comment]
The [Leaflet.FreeDraw](https://github.com/Wildhoney/Leaflet.FreeDraw) plugin implements this feature nicely
It can be tried in [this JSFiddle](https://jsfiddle.net/5oacexuf/1/)
There is a react wrapper for this plugin [react-leaflet-freedraw](https://github.com/elangobharathi/react-leaflet-freedraw) 

A version of this was implemented in Dash Leaflet version `0.1.4rc2`; [example of usage is provided in this issue](https://github.com/thedirtyfew/dash-leaflet/issues/45#issuecomment-696782868)
To move beyond a release candidate for my use cases:
- The map would need to be clearable, [as I was having issues where I would change the map, making the polygons invalid, so tried removing the Freedraw layer but the polygons would remain rendered](https://github.com/thedirtyfew/dash-leaflet/issues/45#issuecomment-697309933)
    - This could be handled by providing access to FreeDraw's [Bundled Methods](https://github.com/Wildhoney/Leaflet.FreeDraw#bundled-methods) to enable clearing / resetting etc
- Dynamic control over polygon attributes such as weight, colour, hover-style etc.
- A nice to have would be being able to individually reference the polygons via a uuid, so can track changes

However, there may be better alternatives to provide this functionality than FreeDraw, especially as concerns were expressed over its size
https://github.com/thedirtyfew/dash-leaflet/issues/45#issuecomment-696728750

**Comment by emilhe** [comment]
A small note; most of the dash-leaflet component have now been ported to use async loading. This means that the size of the free draw dependency i longer an issue; we can just load it async with the system now in place.

**Comment by emilhe** [comment]
Closed due to inactivity. Please re-open if still relevant.

**Comment by biopzhang** [comment]
Hello Emil,

Thank you for the nice tool! It really saves people like me who have little javascript background... I like the freehand drawing function, I think it's very useful especially on Bioimages to draw regions of interest efficiently. 

As far as I can see, in 0.1.4rc2 version, you have made it work perfectly. In the latest version, it's not included yet. A similar function I can find is the "EditControl", however, it seems that you only delete the last polygon vertex, but can not move all the vertices freely. 

At the moment, I'll go with the 0.1.4rc2, and I'm more than interested to use latest version... Do you have a plan to include the features in 0.1.4rc2 in a feature release?

Thank you!!
PZ
