### ISSUE TITLE
GeoJSON mouseover shouldn't call bringToFront

### ISSUE THREAD

**Issue by aaron-kaplan** [thedirtyfew/dash-leaflet#123]
When a `GeoJSON` element has a `hoverStyle` attribute, mousing over a feature causes it to pop to the top of the stacking order, obscuring markers that previously appeared on top of it. It looks like [GeoJSON.react.js#L62](https://github.com/thedirtyfew/dash-leaflet/blob/master/src/lib/components/GeoJSON.react.js#L62) might be the reason.

First of all, in the application I'm currently working on I don't want this behavior, so I would like to be able to disable it. Second, even in cases where I did want the object to pop up on mouseover, I think I would want it to pop back down on mouseout. That currently doesn't happen--once the feature pops to the top, it stays on top forever.

**Comment by aaron-kaplan** [comment]
Hmm, #104 sounds like the same issue, in which case my guess about `bringToFront` being the culprit is wrong. I will try the `Pane` solution. I'm still curious why `bringToFront` is called here.

**Comment by emilhe** [comment]
The implementation was crafted based on the leaflet docs,

https://leafletjs.com/examples/choropleth/

If you have an idea for improving it, I would be happy to look at a PR :)

**Comment by aaron-kaplan** [comment]
Thanks for the pointer. I copied that example and added a marker to it
```
        new L.CircleMarker([39, -98]).addTo(map);
```
and it suffers from the same problem. The marker starts out on top, but when you mouse over Kansas, the polygon leaps up and covers the marker.

Commenting out the call to `bringToFront` does fix that problem, but then there's weird overlapping of the highlighted state's borders with those of its neighbors, as the leaflet docs explain. I don't have a solution yet.

**Comment by aaron-kaplan** [comment]
I had a misunderstanding. I thought that `bringToFront` caused an overlay to be displayed above a marker, but in fact `L.CircleMarker` is not a kind of marker, despite the name. It's a subclass of `L.Path`, and it gets put in the overlay pane, not the marker pane. If I use`L.Marker` instead of `L.CircleMarker`, it  stays on top even after a mouseover event.

If I have a bone to pick, it's with Leaflet (CircleMarker should be a marker), not with dash-leaflet. Thanks for the help!
