### ISSUE TITLE
Variable width arrows in dash-leaflet [help]

### ISSUE THREAD

**Issue by lucasjamar** [thedirtyfew/dash-leaflet#126]
Hi!

Thanks a lot for dash-leaflet. I was wondering, is it possible to set the width of the arrows like the one below from the docs? I am trying to plot flows between borders on a map. Thanks!
https://dash-leaflet.herokuapp.com/#examples

![image](https://user-images.githubusercontent.com/39372418/152751855-cc460a4d-28c2-4141-b7e1-a5c5fe394174.png)

**Comment by emilhe** [comment]
I am not sure I understand the question. The code for the example is included in the docs?

**Comment by lucasjamar** [comment]
My apologies. I just realised I can use the weight argument in Polyline to make the arrow ticker.
This was what I was trying to achieve. I will close the issue and thanks.

![image](https://user-images.githubusercontent.com/39372418/152791384-a3ee5444-2dfb-480a-9652-fdd505bf913f.png)


```
import dash_leaflet as dl
from dash import Dash, html

# Simple arrow.
polyline = dl.Polyline(positions=[[57, -19], [60, -12]])
patterns = [dict(offset='100%', repeat='0', arrowHead=dict(pixelSize=15, polygon=False, pathOptions=dict(stroke=True)))]
arrow = dl.PolylineDecorator(children=polyline, patterns=patterns)

polyline = dl.Polyline(positions=[[57, -19], [40, -12]], weight=10)
patterns = [dict(offset='100%', repeat='0', arrowHead=dict(pixelSize=50, polygon=False, pathOptions=dict(stroke=True)))]
arrow2 = dl.PolylineDecorator(children=polyline, patterns=patterns)

# Create app.
app = Dash()
app.layout = html.Div(
    dl.Map([
        dl.TileLayer(), arrow, arrow2],
        zoom=4, center=(52.0, -11.0)
    ),
    style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}
)

if __name__ == '__main__':
    app.run_server()
```
