### ISSUE TITLE
REQUEST: Tooltip from GeoJSON properties 

### ISSUE THREAD

**Issue by Instatarama** [thedirtyfew/dash-leaflet#128]
I've been looking at implementation of tooltips in GeoJSON. It seems that the tooltip values are meant to be under a key named tooltip in each feature of the GeoJSON. 

Something like this: 

```
{"type":"FeatureCollection",
	"features":[{"type":"Feature", 
		>>"tooltip": "tooltip value here",<<
		"id":"ckan_043f58e0_a188_4458_b61c_04e5b540aea4.1", 
		"geometry":{"type":"Point","
					coordinates":[145.371389,-
								16.993611]},"
					geometry_name":"geom","
					properties":{"name":"512822"}}


```

But often the data that is appropriate for a tooltip would be in the geometry's properties. In this sample GeoJSON file it's the case, and when converting a GeoPandas geodataframe to a JSON it is the same scenario. 
 
```{"type":"FeatureCollection",
	"features":[{"type":"Feature", 
		"id":"ckan_043f58e0_a188_4458_b61c_04e5b540aea4.1", 
		"geometry":{"type":"Point","
					coordinates":[145.371389,-
								16.993611]},"
					geometry_name":"geom","
					properties":{"name":"512822","
								facility_id":512822,"
								jurisdiction_code":"QLD","
								facility_name":"Glenley","
								latest_report_url":"http://www.npi.gov.au/npidata/action/load/individual-facility-detail/criteria/state/QLD/year/2017/jurisdiction-facility/Q064ILP004"}}
```

My request is to be able to choose the tooltip info from one of the properties keys. Say I wished to have a tooltip with the facility name, jurisdiction_code and latest report url from the above. 

At the moment it is possible to achieve some of this with a dict comprehension to make the tooltip info but it's quite a computationally expensive process, as I have to render arrays of 30-130,000 points that are user-selectable. 

Thanks for your help and an excellent dash module.

**Comment by emilhe** [comment]
Thanks! I designed the default behavior to be that tool tips are picked up from the `tooltip` property if present for convenience. You can customize the behavior via the `onEachFeature` prop as you please.

**Comment by Instatarama** [comment]
Many thanks @Emilhe, I will look into it.
