### ISSUE TITLE
Request: nautical miles unit option for MeasureControl

### ISSUE THREAD

**Issue by jnrobinson** [thedirtyfew/dash-leaflet#130]
Hi,

It would be very nice to have a nautical miles unit option for MeasureControl, which would be useful for maritime and aviation applications.

It seems like this isn't supported because leaflet-measure doesn't yet support NM, but that package hasn't been updated in years. Is there any possible workaround to convert miles to NM?

Thanks,
Joseph

**Comment by emilhe** [comment]
For version `1.0.3`, you can now specify custom units, which should resolve this issue.
