### ISSUE TITLE
ImageOverlay's url and bounds props should accept None

### ISSUE THREAD

**Issue by prl900** [thedirtyfew/dash-leaflet#145]
This is more an enhancement or suggestion for the `ImageOverlay` functionality -- this component is working as documented.

A common case with `ImageOverlay`s is to be able to dynamically define the contents and location of the images through callbacks. In this case, a valid and scenario would be to be able to declare the ImageOverlay component with an `id` but with `None` values for the `url` and `bounds` properties. This currently throws an exception saying that these properties have to be defined.

Thanks

**Comment by emilhe** [comment]
For this usecase, I would instead recommend creating a `LayerGroup` as a container, and then update it's children with a new `ImageOverlay` component.
