### ISSUE TITLE
Define Directional Patterns (like dashes, arrows, icons, etc.) on Polylines

### ISSUE THREAD

**Issue by NightFury555** [thedirtyfew/dash-leaflet#15]
Hi!

Thank you for coming out with this really good package and all your swift responses.

I was trying to plot some routes via dash-leaflet.Polyline(). However, I was thinking if it is possible to also has directional indication like arrows along the path of the plotted route?

There is something similar, [Polyline Decorator](https://github.com/bbecquet/Leaflet.PolylineDecorator), but is a Js leaflet plug-in.
Thanks!

**Comment by emilhe** [comment]
I have just (0.0.14) implemented a wrapper of the leaflet plug-in. It was not completely plug and play, so i had to make a few changes to the interface. You can find examples [here](https://dash-leaflet.herokuapp.com/#polyline_decorator).

**Comment by NightFury555** [comment]
> I have just (0.0.14) implemented a wrapper of the leaflet plug-in. It was not completely plug and play, so i had to make a few changes to the interface. You can find examples [here](https://dash-leaflet.herokuapp.com/#polyline_decorator).

Thank you for adding this new feature! Can see that you have put into a lot of time and effort into your work.

I have been trying out. However, I realise there could be some issues.
- The very first plot shows that the list of PolylineDecorators and its respective polylines get plotted correctly.
- However, subsequent filters (and callbacks) shows that only the the polylines get plotted but not the respective arrows. i.e. The polylines are responsive to my filters but the arrows aren't, and the very first arrows still remain after the filter.

**Comment by emilhe** [comment]
Could you post some example code? You might just be experiencing that the i have implemented the properties as static, i.e they cannot be changed after construction. To change a decorator, you must replace it by a new one.

**Comment by NightFury555** [comment]
> Could you post some example code? You might just be experiencing that the i have implemented the properties as static, i.e they cannot be changed after construction. To change a decorator, you must replace it by a new one.

Not a problem, I have attached a code snippet in a text file for easier viewing.
[Example.txt](https://github.com/thedirtyfew/dash-leaflet/files/4644803/Example.txt)

In a case where a callback is needed, how do you "erase" the previous plot and replace with a new one?

**Comment by emilhe** [comment]
I would attach the object (in the case a decorator) as the child of a layergroup and target the children of the layergroup as the callback output. I can post an example when I get near a pc.

**Comment by emilhe** [comment]
Here is a small example that works with the current code,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input

def draw(n):
    patterns = [dict(offset='5%', repeat='10%', marker={})]
    positions = [(56, 9.5 + 0.1 * i) for i in range(n)]
    polyline = dl.Polyline(positions=positions)
    return dl.PolylineDecorator(polyline, patterns=patterns, id=str(n))  # the id MUST change

# Create app.
app = dash.Dash()
app.layout = html.Div([dl.Map([dl.TileLayer(), dl.LayerGroup(draw(2), id="container")],
                              zoom=10, center=(56, 10)), html.Button("Click me", id="btn")],
                      style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})

@app.callback(Output("container", "children"), [Input("btn", "n_clicks")])
def func(n_clicks):
    return draw(n_clicks + 2)

if __name__ == '__main__':
    app.run_server()
```

Note that you must change the id of the decorator when you update it. Otherwise, the map will not detect that it has changed, and it will thus to be redrawn.

While the above example _works_, i agree that it is not super intuitive. I'll try to think about a way to make it better.

**Comment by emilhe** [comment]
I have just (0.0.15rc1) changed the `positions` and `children` properties of the decorator to dynamic rather than static. Hence, the above code can now be simplified to,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input


def draw_polyline(n):
    return dl.Polyline(positions=[(56, 9.5 + 0.1 * i) for i in range(n)])


patterns = [dict(offset='5%', repeat='10%', marker={})]
decorator = dl.PolylineDecorator(draw_polyline(2), patterns=patterns, id="decorator")
# Create app.
app = dash.Dash()
app.layout = html.Div([dl.Map([dl.TileLayer(), decorator], zoom=10, center=(56, 10)),
                       html.Button("Click me", id="btn")],
                      style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})


@app.callback(Output("decorator", "children"), [Input("btn", "n_clicks")])
def func(n_clicks):
    return draw_polyline(n_clicks + 2)


if __name__ == '__main__':
    app.run_server()

```

**Comment by NightFury555** [comment]
> Here is a small example that works with the current code,
> 
> ```
> import dash
> import dash_html_components as html
> import dash_leaflet as dl
> from dash.dependencies import Output, Input
> 
> def draw(n):
>     patterns = [dict(offset='5%', repeat='10%', marker={})]
>     positions = [(56, 9.5 + 0.1 * i) for i in range(n)]
>     polyline = dl.Polyline(positions=positions)
>     return dl.PolylineDecorator(polyline, patterns=patterns, id=str(n))  # the id MUST change
> 
> # Create app.
> app = dash.Dash()
> app.layout = html.Div([dl.Map([dl.TileLayer(), dl.LayerGroup(draw(2), id="container")],
>                               zoom=10, center=(56, 10)), html.Button("Click me", id="btn")],
>                       style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})
> 
> @app.callback(Output("container", "children"), [Input("btn", "n_clicks")])
> def func(n_clicks):
>     return draw(n_clicks + 2)
> 
> if __name__ == '__main__':
>     app.run_server()
> ```
> 
> Note that you must change the id of the decorator when you update it. Otherwise, the map will not detect that it has changed, and it will thus to be redrawn.
> 
> While the above example _works_, i agree that it is not super intuitive.

Thank you for your example, I have learned some new ways of writing the code :).
I have taken note and tweaked my code to have a different ID for each callback.

**Comment by NightFury555** [comment]
> I have just (0.0.15rc1) changed the `positions` and `children` properties of the decorator to dynamic rather than static. Hence, the above code can now be simplified to,
> 
> ```
> import dash
> import dash_html_components as html
> import dash_leaflet as dl
> from dash.dependencies import Output, Input
> 
> 
> def draw_polyline(n):
>     return dl.Polyline(positions=[(56, 9.5 + 0.1 * i) for i in range(n)])
> 
> 
> # Create decorator.
> patterns = [dict(offset='5%', repeat='10%', marker={})]
> decorator = dl.PolylineDecorator(draw_polyline(2), patterns=patterns, id="decorator")
> # Create app.
> app = dash.Dash()
> app.layout = html.Div([dl.Map([dl.TileLayer(), decorator], zoom=10, center=(56, 10)),
>                        html.Button("Click me", id="btn")],
>                       style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})
> 
> 
> @app.callback(Output("decorator", "children"), [Input("btn", "n_clicks")])
> def func(n_clicks):
>     return draw_polyline(n_clicks + 2)
> 
> 
> if __name__ == '__main__':
>     app.run_server()
> ```

Thanks! Looking forward to the final release!

**Comment by emilhe** [comment]
Are you satisfied with the syntax of the 0.0.15rc1 release (you can try it out right away via pip, i.e. pip install dash-leaflet==0.0.15rc1)? If so, I'll bump it to 0.0.15 (without rc1).

**Comment by NightFury555** [comment]
> pip install dash-leaflet==0.0.15rc1

I have tried it and it works great, that means there is no need to assign a unique ID for each plot.

 For 0.014, I followed your guidance and so assigned each ID to the current datetime so it will always be a unique ID. Hardly the most efficient way haha.. 

0.0.15 would be alot cleaner indeed. Thank you!

**Comment by emilhe** [comment]
Great! Thanks for the quick test. I also like the new syntax much better.
