### ISSUE TITLE
dl.Popup HTML code is rendering as a string instead of actual HTML

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [thedirtyfew/dash-leaflet#154]
Wassoup everyone,

I've run into a roadblock that I can't seem to solve. I'm creating a list of Markers with associated popups and information that's populated from a Pandas dataframe. I have a function that does this for me:
https://github.com/perfectly-preserved-pie/larentals/blob/master/dataframe.py#L52-L222

I am able to make HTML-formatted popups just fine using that function with this line:
```markers = [dl.Marker(children=dl.Popup(popup_html(row), closeButton=True, maxHeight=100, maxWidth=5), position=[row.Latitude, row.Longitude]) for row in df.itertuples()]```

Unfortunately, I've discovered this is causing _significant_ slowdowns in the Dash app whenever a callback is fired (which is often because I have a LOT of user inputs). I was able to solve it by using my ` popup_html` function to generate the popup HTML code _once_ and insert it into a column in the Pandas dataframe:

```
for row in df.itertuples():
        df.at[row.Index, 'popup_html'] = popup_html(row)
```

and then I generate the popups by referencing the `popup_html` property/cell value for each row:

```
# Create markers & associated popups from dataframe
markers = [dl.Marker(children=dl.Popup(row.popup_html, closeButton=True, maxHeight=15), position=[row.Latitude, row.Longitude]) for row in df_filtered.itertuples()]
```

That makes all the markers appear instantly on the map which is great! But the resulting popups are all formatting as a string for some reason?
![image](https://user-images.githubusercontent.com/28774550/189000186-0ef9f268-78aa-41e1-881f-eb6dd726cc1d.png)

Why would that happen?

**Comment by emilhe** [comment]
My first guess would be that Pandas casts your object structure to a string. Did you try storing your pre-processed html in a list?

**Comment by perfectly-preserved-pie** [comment]
> My first guess would be that Pandas casts your object structure to a string. Did you try storing your pre-processed html in a list?

Yeah. My function returns a list (using [ and ] notation). If I pick a random row in the dataframe, the cell is a list:
```
>>> type(df.iloc[4].popup_html)
<class 'list'>
```

**Comment by perfectly-preserved-pie** [comment]
Actually, you're on to something. While the above remains true, I added a print debug statement in the Dash callback:
```
# Create markers & associated popups from dataframe
markers = [dl.Marker(children=dl.Popup(row.popup_html, closeButton=True, maxHeight=15), position=[row.Latitude, row.Longitude]) for row in df_filtered.itertuples()]
[print(type(row.popup_html)) for row in df_filtered.itertuples()]

```

And now I'm seeing that the object type is now a string:
```
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
```

Which still confuses me. How can it be a normal Dash object while stored in the dataframe but suddenly change into a string when iterated over?

**Comment by perfectly-preserved-pie** [comment]
Finally found [the right StackOverflow post](https://stackoverflow.com/questions/23111990/pandas-dataframe-stored-list-as-string-how-to-convert-back-to-list), lol.

Saving my dataframe as a pickle instead of a CSV fixed the problem. The object type is preserved as a list and the popups render HTML properly now. It wasn't a problem with Dash Leaflet like I assumed, just a thing with Pandas. Thanks for the assist though, you got me on the right track.
