### ISSUE TITLE
Support for bringToFront/bringToBack Feature

### ISSUE THREAD

**Issue by SimonKnorke** [thedirtyfew/dash-leaflet#16]
Hello!

A nice feature would be the ability to arrange the available layers on the map so that you have control over overlapping polylines and markers.
Especially when you create interactive Polylines/Markers on the map, you might want to place certain components in the foreground or background.

The corresponding Leaflet documentation is
https://leafletjs.com/reference-1.6.0.html#path-bringtofront and
https://leafletjs.com/reference-1.6.0.html#path-bringtoback

Or can you think of a quick solution? I have tried to achieve this by the order of the LayerGroups and marker creation but with no success.

**Comment by emilhe** [comment]
A have just (0.0.16) added a `Pane` component to enable a more finegrained control of layer ordering. Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl

app = dash.Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dl.Map([dl.Pane([dl.CircleMarker(center=(56, 10), fillOpacity=1)], style={"z-index": 101}),
            dl.Pane([dl.CircleMarker(center=(56, 10), fillColor="red", fillOpacity=1)], style={"z-index": 100})])
], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})

if __name__ == '__main__':
    app.run_server()
```

If you switch the z-index of the markers, the ordering in which they are drawn should change.

**Comment by SimonKnorke** [comment]
Hey, that component is a nice idea! But something doesn't seem to work yet.
When adding the `dl.Pane` component the website is not rendering. By the way your example is missing a `dl.TileLayer`.

**Comment by emilhe** [comment]
I am happy that you like the idea. I figured this concept would fit better in the Dash context as compared to the bringToFront/bringToBack functions. It seems something went wrong in the build process of (0.0.16); i am sorry for that. I just pushed (0.0.17); please try that one instead.

**Comment by SimonKnorke** [comment]
Well done, now it works for me! I'll let you know if I notice any problems.
I completed your small example to control two overlapping circles on a map with the z-index. It's also important to put the `dl.TileLayer` in a `dl.Pane` component.

```
import dash
import dash_html_components as html
import dash_leaflet as dl

map_components = [
	dl.Pane([dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png")], style={"z-index": 0}),
	dl.Pane([dl.CircleMarker(center=(56, 10.8),  radius=100, fillOpacity=1)], style={"z-index": 1}),
	dl.Pane([dl.CircleMarker(center=(56, 10.5), radius=50, fillOpacity=1, color='red')], style={"z-index": 2})
]

app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
	dl.Map(id="map", children=map_components, center=[56, 11], zoom=9, 
	style={'width': "100%", 'height': "500px"})
])

if __name__ == '__main__':
    app.run_server()
```

**Comment by emilhe** [comment]
Great! It is not strictly necessary to wrap the TileLayer in a Pane. If you don't, it will be added to the default tile pane, which has z-index=200. Hence the circles should have a z-index higher than this.

**Comment by SimonKnorke** [comment]
Yeah, I just noticed that and removed my code sample:) Yours works fine, thanks!

**Comment by doemuu00** [comment]
Hi @emilhe

I'm trying to find a way to change the order of a number of `dl.Overlay`, controlled by a `dl.LayerControl`. The question seems to have come up before but I couldn't find a conclusive answer. The idea using `dl.Pane` works of course but it doesn't provide a solution for controlled layers. Any ideas/plans there? Thanks!
