### ISSUE TITLE
GeoJSON only accepts FeatureCollections

### ISSUE THREAD

**Issue by aaron-kaplan** [thedirtyfew/dash-leaflet#160]
Leaflet's GeoJSON component can handle any GeoJSON object (Feature, Polygon, Line,...), but dash-leaflet's GeoJSON component [fails](https://github.com/thedirtyfew/dash-leaflet/blob/master/src/lib/utils.js#L57) unless `data` has a `features` attribute, which only FeatureCollections have. Is that assumption really necessary?

If this restriction can't be relaxed, it should at least be documented. When I wanted to display a single shapely geometry on the map, it took a lot of digging to figure out that I had to wrap it in a FeatureCollection. The examples  currently all use GeoJSON produced by `dicts_to_geojson`, which is no help if you already have the GeoJSON that you want to use.

**Comment by emilhe** [comment]
Yes, I designed the component with the expectation that the user supplies a `FeatureCollection`. But I don't see any reason this assumption couldn't be lifted. All example data I have been worked with have just been `FeatureCollection`s, so I never tested single geometries.

But, as I understand, you can still realize the desired visualization, right? Hence, this bug report is about adding support for a simpler syntax (to achieve the same thing)?

**Comment by aaron-kaplan** [comment]
> But, as I understand, you can still realize the desired visualization, right? 

Yes. The problem I'm reporting is that it was hard to figure out how to do it. The problem could be solved by some combination of relaxing the constraint, improved error messages, or adding documentation about how to display arbitrary GeoJSON that doesn't necessarily come from `dicts_to_geojson`.

**Comment by emilhe** [comment]
Yeah, I agree that it could be better. But it's not just GeoJSON originating from `dicts_to_geojson` that works. All example data I have tried so far have worked, e.g. https://leafletjs.com/examples/choropleth/

**Comment by emilhe** [comment]
From version `1.0.2`, single features are also supported.
