### ISSUE TITLE
http://dash-leaflet.herokuapp.com/ is offline

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [thedirtyfew/dash-leaflet#165]
Hi, I'm trying to view the SuperCluster documentation but the website is offline. 

![image](https://user-images.githubusercontent.com/28774550/206871057-5f6bb3ee-0f69-429e-942f-750197e33240.png)

**Comment by emilhe** [comment]
Yes, Heroku has taken down the docs as they have discontinued their free tier. You can use Render for now,

https://dash-leaflet-docs.onrender.com

**Comment by perfectly-preserved-pie** [comment]
Perfect, thank you!
