### ISSUE TITLE
Unable to set scrollWheelZoom argument for dl.Map()

### ISSUE THREAD

**Issue by David-LiCause** [thedirtyfew/dash-leaflet#17]
@emilhe Thanks for your work on this package! It's incredibly useful

When instantiating a `dash_leaflet.Map()` object the `scrollWheelZoom` parameter isn't accepting boolean arguments.

Code to reproduce:
```
import dash  # 1.12.0
import dash_leaflet as dl  # 0.0.16

app = dash.Dash()
app.layout = dl.Map(
    dl.TileLayer(),
    style={'width': '1000px', 'height': '500px'},
    scrollWheelZoom=False)

if __name__ == '__main__':
    app.run_server(debug=True)
```

Error message:
![image](https://user-images.githubusercontent.com/16857189/82612923-58bba380-9b81-11ea-8262-aa35e5e7f57b.png)

**Comment by emilhe** [comment]
Thanks! I just (0.0.17) corrected the type verification of the `scrollWheelZoom ` parameter, so it should work now :)

**Comment by David-LiCause** [comment]
Awesome, thanks for your help! I just updated the package and the `scrollWheelZoom` parameter is working now
