### ISSUE TITLE
"bounds" attribute of TileLayer not working

### ISSUE THREAD

**Issue by meowsome** [thedirtyfew/dash-leaflet#170]
Hello,

I am trying to set the `bounds` attribute on a `TileLayer`, but I can't seem to figure out how to pass coordinates to it. I am also not sure what format to pass the coordinates. In the documentation of TileLayer, it says the I should pass a `list of numbers`. 

I have tried the following:

When I pass `[lon_min, lat_min, lon_max, lat_max]` it gives the error: `Cannot read properties of undefined (reading 'lat')`.

When I pass `[[lon_min, lat_min], [lon_max, lat_max]]` it gives the error: 
```
Invalid argument `bounds[0]` passed into TileLayer with ID "test".
Expected `number`.
Was supplied type `array`.
```

Here is where my TileLayer is:
```
dl.Map([
        dl.TileLayer(),
        dl.TileLayer(
            opacity=0.5,
            url="/assets/output_files/{z}/{x}_{y}.jpeg",
            noWrap=True,
            tileSize=200,
            bounds=[[lon_min, lat_min], [lon_max, lat_max]],
            id='test'
        ),
        ],
        zoom=5,
        center=(lon_start, lat_start),
        style={'width': '100%', 'height': '90vh', 'zIndex': '1'},
        id='image_map'
    )
```

I was wondering if you could please look into this? I tried to get this set up locally to investigate the error further but couldn't figure it out yet.

**Comment by emilhe** [comment]
You need to specify the corners, like states in the [Leaflet docs](https://leafletjs.com/reference.html#latlngbounds). Something like,

```
TileLayer(id=target_id, url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", bounds=[[40.712, -74.227],
    [40.774, -74.125]])
```
