### ISSUE TITLE
Docs? 

### ISSUE THREAD

**Issue by scattered-development** [thedirtyfew/dash-leaflet#174]
Hi 

I think the docs used be hosted on Heroku, which is sadly no longer free. 

Any chance of getting them up and running again on free python-anywhere? 

I would be happy to do this for you, if you can provide me with the app?

**Comment by emilhe** [comment]
I have moved it to render, which is still free 😊

https://dash-leaflet-docs.onrender.com

**Comment by scattered-development** [comment]
sweet you're the best! Like you really are, all this dah work you do is amazing...cheers
