### ISSUE TITLE
MarkerClusterGroup callback

### ISSUE THREAD

**Issue by karellagast** [thedirtyfew/dash-leaflet#177]
Hello everyone, I was wondering if I can use a callback on a dl.MarkerClusterGroup? And when clicking on one of the markers on my dl.Map (cities in the world) I need to a callback that when I click on the marker for that city, I can execute some code. I manage to get a callback on one dl.Marker but not a callback on a dl.MarkerClusterGroup. 
Any suggestions?
Thank you in advance
Karel Lagast

**Comment by emilhe** [comment]
I would suggest to use the `GeoJSON` component instead. It has superior performance, and your use case is supported.
