### ISSUE TITLE
canvas renderer and option "tolerance"

### ISSUE THREAD

**Issue by ascheidl** [thedirtyfew/dash-leaflet#178]
Hello,

I want to increase the area around my features in which they become clickable.

As far as I understood, in leaflet this is possible using the canvas renderer and it's option "tolerance".

However, I could not find out how to activate the canvas renderer and how to set this option in dash_leaflet.

Can you help ?

**Comment by emilhe** [comment]
Yes, should be possible from the `1.0.1` release on onwards. As noted the [component reference](https://www.dash-leaflet.com/components/map_container), you can pass a `renderer` argument to the `Map`, specifying which renderer to use - and specify any options to pass on to it.
