### ISSUE TITLE
Live tracking marker or similar

### ISSUE THREAD

**Issue by 2gmlaso** [thedirtyfew/dash-leaflet#179]
Hi, Firts of all, congrats on putting together this awesome project

I have been triying to figure it out to do a live tracker marker o something like this, so Is there a way to implement this plugin into dash-leaftlet or make a marker that updates his position on the map like that ?

[https://github.com/alexandra-c/leaflet-tracking-marker](url) 
[https://leavittmapping.com/projectpages/livetrackingdashboard](url)

**Comment by emilhe** [comment]
I believe the answer is _yes_ to both options. I don't see any immediate blockers in writing a small wrapper for the plugin, in which case you would be able to use the functionality "directly". I believe this would be the best solution. An alternative would be to update a marker using a (clientside) callback. I guess it would be possible to emulate the behaviour of the plugin this way, but it would be a bit less elegant (and the performance would be poor, unless you use a clientside callback).
