### ISSUE TITLE
Plugin to measure distances

### ISSUE THREAD

**Issue by SimonKnorke** [thedirtyfew/dash-leaflet#18]
Hi! 

It would be an amazing feature to have a measuring tool (like the button for location service) to create a polyline attached with its distance.

There are some solutions for `leaflet.js` out there such as
https://github.com/NLTGit/Leaflet.LinearMeasurement
https://github.com/ppete2/Leaflet.PolylineMeasure

It's also possible to do this via a checkbox and dash callbacks (compute distance from the maps `click_lat_lng` to `dbl_click_lat_lng`). However, I think that an integrated widget would be very useful for many people. Can you think of a future support for this plugin?

Anyway, thanks for your great package!

**Comment by emilhe** [comment]
Thanks! A measurement control could be an option. In addition to your suggestions, I stumbled on this one,

https://github.com/ljagis/leaflet-measure

It seems to be popular, but not maintained. Your first link seems like a simpler component though.

**Comment by SimonKnorke** [comment]
I agree that the first variant (Leaflet.LinearMeasurement) is more intuitive in use, but the double click event doesn't seem to work on my mobile device. Is there maybe an easy way to trigger the event to finish the measurement like in the "leaflet-measure" example? 
If not, I would prefer the option "leaflet-measure" found by you because of the mobile compatibility.

**Comment by emilhe** [comment]
For now, i think this issue is out of scope.
