### ISSUE TITLE
Error in EditControl Minimal example - No context provided

### ISSUE THREAD

**Issue by rmourgues31** [thedirtyfew/dash-leaflet#184]
Hello,

When replicating the example from https://dash-leaflet.herokuapp.com/#edit_control, I immediately get an error : `No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>`.

Is this normal ? How can it be fixed ?

Thanks

**Comment by prl900** [comment]
Yes, seems this has broken recently. I cannot recover the functionality of EditControl even after downgrading to previous releases of dash-leaflet. Any ideas about how to fix this @emilhe? Thanks

**Comment by prl900** [comment]
Thanks @emilhe. Version `0.1.23` seems to work well so as you suggested using this version is a simple fix for apps that require this functionality.

 It's great to hear you are looking into updating the library. I hope we can see the new improved version soon. Thanks for your work.

**Comment by rmourgues31** [comment]
Thanks for the reply, I switched to `0.1.23` and it's fine for my purpose. Thank you for all the work !

**Comment by emilhe** [comment]
Fixed in the `1.0.1` release. Demo here: https://www.dash-leaflet.com/components/controls/edit_control

**Comment by rmourgues31** [comment]
Awesome ! Thanks for your fantastic work
