### ISSUE TITLE
Use side by side plugin

### ISSUE THREAD

**Issue by diogocaribe** [thedirtyfew/dash-leaflet#185]
Is there any way to use side by side plugin (https://github.com/digidem/leaflet-side-by-side) in dash-leaflet?

**Comment by emilhe** [comment]
It would require the implementation of a Dash wrapper component. I'll be happy to look a PR if you decide to go down that route.

**Comment by diogocaribe** [comment]
Do you have some material that I can see where I can start?

**Comment by emilhe** [comment]
I would recommend to take a look at the source code starting with a simple component like the `EasyButton`,

https://github.com/thedirtyfew/dash-leaflet/blob/master/src/lib/components/EasyButton.react.js

to get a basic understand of how the wrapping process works :)

**Comment by diogocaribe** [comment]
I need more and more experience to do it. I don't belive that I'm read to do it now. I've read the code, and what I understood is that I need to code react.js of LeafletSideBySide.js.
