### ISSUE TITLE
'Map click events' example in documentation does not update click position correctly

### ISSUE THREAD

**Issue by serenekeeper** [thedirtyfew/dash-leaflet#19]
Hover info for the marker is not getting updated for **second and subsequent** clicks. 
Instead of using 'title' for hover info, its better to use Tooltip

**Comment by emilhe** [comment]
Ah, you are right. I guess it's due to the map not properly detecting the change. It can be solved by assigning a unique id to the marker, e.g. like this

```
import dash
import dash_html_components as html
import dash_leaflet as dl

from dash.dependencies import Input, Output

app = dash.Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dl.Map([dl.TileLayer(), dl.LayerGroup(id="layer")],
           id="map", style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}),
])


@app.callback(Output("layer", "children"), [Input("map", "click_lat_lng")])
def map_click(click_lat_lng):
    tooltip = "({:.3f}, {:.3f})".format(*click_lat_lng)
    return [dl.Marker(position=click_lat_lng, title=tooltip, id=tooltip)]


if __name__ == '__main__':
    app.run_server()
```
Would you still argue that Tooltip is better suited? Do you have any references?

**Comment by emilhe** [comment]
I have update the documentation to use a `Tooltip` in the map click events example as well as the marker cluster example.
