### ISSUE TITLE
Minichart tooltip and popup

### ISSUE THREAD

**Issue by jjsoper** [thedirtyfew/dash-leaflet#190]
Hi there,

I'm wondering if there are plans to incorporate support for tooltips/popups and legends into leaflet minicharts? Some examples are shown in the R version (https://github.com/rte-antares-rpackage/leaflet.minichart).

Thanks for all of your hard work!

**Comment by emilhe** [comment]
Unfortunately, the `leaflet.minichart` component seems to have been abandoned,

https://github.com/rte-antares-rpackage/leaflet.minichart

The current version is not compatible with the latest version of Leaflet, and I am thus currently considering if it should be included in `dash-leaflet` in the future or not.

**Comment by emilhe** [comment]
In the new major version (1.0.0 or newer), `Minichart` is no longer included. If it is added again, please reopen the issue.
