### ISSUE TITLE
How to remove the Leaflet attribution?

### ISSUE THREAD

**Issue by araichev** [thedirtyfew/dash-leaflet#192]
Within Leaflet one can achieve this via `map.attributionControl.setPrefix('')` according to [this issue](https://github.com/Leaflet/Leaflet/pull/8109).
How can one do this with Dash Leaflet?

**Comment by emilhe** [comment]
In the upcoming version 1.0.0, you can pass `attributionControl=False` to the `Map` component.

**Comment by emilhe** [comment]
Should be solved in the `1.0.1` release. Here is a demo: https://www.dash-leaflet.com/components/controls/attribution_control
