### ISSUE TITLE
MeasureControl is jerking in version 0.1.28

### ISSUE THREAD

**Issue by araichev** [thedirtyfew/dash-leaflet#193]
Every time i click to add a new point using the MeasureControl, the map shifts rightwards and downwards.
Here's a GIF illustrating the issue: 
![leaflet_measure_jerk](https://github.com/thedirtyfew/dash-leaflet/assets/4087432/e0089b6a-4080-44c0-b1fd-bf8acbe8d046)

This does not happen in versions <= 0.1.25.

**Comment by emilhe** [comment]
This is a known issue due to version incompatibilities. It will be fixed as part of the `1.0.0` release.

**Comment by emilhe** [comment]
Should be solved in the `1.0.1` release. Here is a demo: https://www.dash-leaflet.com/components/controls/measure_control
