### ISSUE TITLE
Support for divIcon

### ISSUE THREAD

**Issue by rsandler00** [thedirtyfew/dash-leaflet#2]
Hi, 

Great package! I want to use [divIcon](https://leafletjs.com/reference-1.6.0.html#divicon) as my Icon. Is there support for that? Is that in the plans?

Also, I realize this isn't an issue, but wasn't sure where else to post. Is there a better place?

Thanks!

**Comment by emilhe** [comment]
Thanks! There is currently no support for `DivIcon`, and i have no immediate plans to implement it. However, i would be happy to look at a pull request, if you decide to give it a go.

**Comment by emilhe** [comment]
I have just (0.0.18rc1) created a `DivMarker` component, which makes is possible to use div icons. Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl

app = dash.Dash()
app.layout = html.Div([dl.Map([dl.TileLayer(), dl.DivMarker(position=(56,10), iconOptions=dict(className='my-icon'))]),
], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})

if __name__ == '__main__':
    app.run_server()
```

where the class `my-icon` is contained in a .css file in the assets folder,

```
.my-icon
{
  background:red;
  border:5px solid rgba(255,255,255,0.5);
  color:blue;
  font-weight:bold;
  text-align:center;
  border-radius:50%;
  line-height:30px;
}
```

To add components to the marker, simply pass them as children to the `DivMarker` component. They will then be rendered as part of the marker, and you should be able to use them as normally (with callbacks etc.).

**Comment by christianwengert** [comment]
Already works likes this on 0.0.18
