### ISSUE TITLE
Additional plugins for opacity and polygon drawing

### ISSUE THREAD

**Issue by hhoeflin** [thedirtyfew/dash-leaflet#22]
Hi,

you have put together a great app here. I was wondering if you would be willing to add support for 2 plugins:

A plugin to control showing of layers and their opacity:
https://github.com/dayjournal/Leaflet.Control.Opacity

Also in your heroku example you show how you could draw polygons. Here is a plugin that takes this to the next level:

https://github.com/geoman-io/leaflet-geoman

Thanks!

**Comment by emilhe** [comment]
Thanks! I will think about adding the opacity control. It should be relatively simply to implement. However, it would also be relatively easy to achieve the same behavior via a Dash callback. 

The leaflet-geoman plugin seems super cool! It's pretty comprehensive though, so i don't think i will be porting it any time soon. My initial idea of this library was to implement the "basic stuff", and then people can implement more advanced features in their own applications. From this point of view, i am not sure that leaflet-geoman is within the scope of this library ;)

**Comment by hhoeflin** [comment]
ok, thanks - fair enough!

**Comment by hhoeflin** [comment]
Additional question from my side: Do you know if it would work to wrap a plugin such as geoman outside of your package? I assume leaflet geoman needs access to the leaflet javascript - does that work with an external package?

**Comment by emilhe** [comment]
I guess it would be possible. It would need access to leaflet yes, but i would assume that it is possible to do the linking somehow (i haven't written much JS, so i would have to do some digging to find out how it works).

**Comment by hhoeflin** [comment]
Hi - I just quickly wanted to ask about the opacity control if you still plan to implement it. And congrats - the additional features in the package look awesome. Especially the passing of functions that you recently added is great.

Given that so many packages and features that you have added are actually pretty complex - have you reconsidered the scope of the library (e.g. you said earlier geoman is not basic enough).

Thanks!

**Comment by emilhe** [comment]
Thanks! The next control that i am thinking about implementing is the `LayersControl` (#3 ). However, i haven't figured out how to solve the object flow in Dash (yet). At a glance, the `OpacityControl` would require solving the same issue(s). Hence if (when) i get the `LayerControl` implemented, i might look at the `OpacityControl` next.

I am still not sure if geoman library might be too complex for dash-leaflet, but i think the implementation would require a significant amount of work. And i guess most of the feature could be implemented via Dash (although it would require a decent amount of code). If i need it for another project, i might give it a go :)
