### ISSUE TITLE
Set map zoom level inside callback

### ISSUE THREAD

**Issue by nistran** [thedirtyfew/dash-leaflet#25]
Hi 
I'm wondering if there is a way to set the map canter and zoom level inside callbacks. 
For now I'm able to set the zoom level while creating the map, but not when I'm update the marker data. The idea is to reset the zoom level when markers are added. 

Thanks in advance.

**Comment by nistran** [comment]
I spend some time now with that issue. I'm am able to change the zoom level inside a callback by registering the Output to the zoom attribute of the map. This works as expected until the user zooms on the map. From this point on I'm not able to change the zoom level by code. 
Maybe you guys have some ideas?

**Comment by nistran** [comment]
I think I was able to track down the problem. 
The main problem is, that the actual zoom level (zoomed by the user) is not updated in the zoom map state. So in my example there is still the zoom level, which is set on init. So while I'm trying to reset the zoom level to the default level nothing happens, because there is no value change in the zoom property. 
I now have a workaround by reading the zoom level state and checking for equality to the default zoom level. I then slightly change that level to generate a change event. 
In my eyes this is a bug. 
@emilhe What is your guess about that. 
Thanks!

**Comment by emilhe** [comment]
Hi nistran,

I haven't had time to look into the code, but i suspect that what you are experiencing might not be a bug. Could it be related to the "Manipulating the viewport" comments here?

https://react-leaflet.js.org/docs/en/components

If so, it might help to set the `viewport` property directly (rather then the `zoom`). I'll take a look at the code when i find some time.

\emher

**Comment by nistran** [comment]
Hi emilhe
Thanks for your answer.
The "Manipulating the viewport" comments describes exactly my experience. As I understand it is only possible to solve this with callbacks to trigger on zoom and viewpoint changes. 
So for now I'm good with my workaround.

**Comment by annunal** [comment]
dear all,

the page that was suggested as workaround for this problem 

https://react-leaflet.js.org/docs/en/components

does not exisat NY MORE,

Can ypu describe what you did to solve the issue of getting the zoom level after user changes ?

Thanks
Alessandro
