### ISSUE TITLE
Support for Leaflet Legends

### ISSUE THREAD

**Issue by SimonKnorke** [thedirtyfew/dash-leaflet#3]
Hi,

First of all: Awesome package and amazing work you have done! That's really what I was locking for.
 
Second: I coudn't find a dash-leaflet component for a leaflet Legend.
I am visualizing different grouped Layers (e.g. a Polyline and some Markers).
I want to create a Legend showing the Color (or Icon) of the group and a description. 
Is this possible with this package? Thanks in advance for any help.

Best,
Simon

**Comment by emilhe** [comment]
Thanks! Could you elaborate on which component it is that you had in mind? I don't see a legend component as part of the official leaflet library,

https://react-leaflet.js.org/docs/en/components

Anyhow, if all you need is a static legend, a possible solution could be to add the legend on top of the map container and position it via css.

**Comment by SimonKnorke** [comment]
Sorry, I think it's called "Layers Control" in leaflet. https://leafletjs.com/examples/layers-control.
Depending on the set types of layers (base layers and overlays) you can create a control field on the top of your map by 

L.control.layers(baseMaps, overlayMaps).addTo(map);

I couldn't find this control option in dash-leaflet.

But thanks for your static legend advice! How can you set the location of this legend container? Do you have to set the "bounds"-parameter like in an ImageOverlay?

**Comment by emilhe** [comment]
Thank you for clarifying. There is currently no implementation of the control layers component, but it might be added in the future. If you decide to do an implementation yourself, i would be interested to see a merge request. 

About my previous suggestion; i was actually just thinking about positioning it via CSS on top of the map component. In fact, now that i think about it, it does not even have to be static; you can add any elements/interactions that you like using standard Dash syntax. Here is a small example, where a marker can be toggled on the map,

```
import dash
import dash_daq as daq
import dash_leaflet as dl
import dash_html_components as html
from dash.dependencies import Output, Input

app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    # Map component.
    dl.Map(children=[
        dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"),
        dl.Marker(id="marker", position=(56, 10))
    ], style={'width': "100%", 'height': "100%"}, center=[56.05, 10.25], zoom=10),
    # Legend container.
    html.Div(style={"position": "absolute", "top": "5px", "right": "10px", "z-index": "1000"},
             # Add any elements you like; text, icons, buttons etc.
             children=[daq.ToggleSwitch(id="toggle", label="Marker", labelPosition='bottom')])
], style={"position": "relative", 'width': '1000px', 'height': '500px'})

@app.callback(Output("marker", "opacity"), [Input("toggle", "value")])
def toggle_marker(value):
    return "1" if value else "0"

if __name__ == '__main__':
    app.run_server(debug=False)
```

**Comment by SimonKnorke** [comment]
Thank you very much for your responses!

Unfortunately I' m not sufficiently familiar with leaflet/javascript to implement this by myself. Your proposed Dash solution seems to be a good alternative solution!

**Comment by emilhe** [comment]
The `LayersControl` is finally (0.1.4) here! 

https://dash-leaflet.herokuapp.com/#layers_control

**Comment by janjaappape** [comment]
Couldn't agree more with SimonKnorke, amazing package! However, I'm also looking for  a way to create automatic legends based on (Circle)Markers or Polygon layers. My current solution is to make an image of the markers and add the legend as an image on top of the map. Is there an alternative way to do this?
