### ISSUE TITLE
Getting Current Zoom Level on Map

### ISSUE THREAD

**Issue by reinholtk24** [thedirtyfew/dash-leaflet#34]
I have a callback to get zoom level: 
```python
@app.callback(
    Output("test_zoom_output", "children"),
    [Input("map","zoom")])
def zoom_event(zoom):
    print("Current Zoom Level", zoom)
    return zoom
```

I would like to be able to change the size of the map based on the zoom level (In the example above I am just outputting it to a div name test_zoom_output). The issue is, the above callback is never fired because the prop zoom is a setter and once it is initialized, the value isn't updated (this is what I gathered from the source code in Map.react.js ). Is there a way to expose the zoom event that is used in leafletjs? It can be found here https://leafletjs.com/reference-1.6.0.html#map-option under Map State Change Events
zoom | Event | Fired repeatedly during **any** change in zoom level, including zoom and fly animations.

**Comment by emilhe** [comment]
The callback should fire, though not continuously. I have just tested it (with version 0.0.22), and it works as expected,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
import dash_leaflet.express as dlx
import json

from dash.dependencies import Input, Output

# Create example app.
app = dash.Dash()
app.layout = html.Div([
    dl.Map([dl.TileLayer()], id="map", style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}),
    # Logging element.
    html.Div(id="log")
])


@app.callback(Output("log", "children"), [Input("map","zoom")])
def zoom_event(zoom):
    print("Current Zoom Level", zoom)
    return zoom


if __name__ == '__main__':
    app.run_server()
```
For performance reasons, the callback only fires when the zoom action finished (and not continuously during the action.

**Comment by reinholtk24** [comment]
Thank you for the quick response. Thank you for contributions on this project as well. It's really helpful!!! 

I'm was using version 0.0.17 
Updated my version and worked like a charm. Thanks again.
