### ISSUE TITLE
WMSTileLayer making bad requests

### ISSUE THREAD

**Issue by Folgrim** [thedirtyfew/dash-leaflet#35]
WMSTileLayer seems to be including extraneous properties in it's GetMap requests, even those that aren't relevant to the WMS server, including dash properties such as id, loading_state, setProps, children, etc.

In some cases, this is simply very insecure but the WMS server ignores the extra properties and still responds fine.  In other cases, the WMS server will fail the request thanks to these extraneous properties.  The worst culprit for this being the passing of setProps.

**Comment by Folgrim** [comment]
For anyone else with this issue, my current workaround is to explicitly delete any issue-causing parameters in the min.js after everything is constructed.

ex:
delete(this.wmsParams.setProps);

**Comment by emilhe** [comment]
Ah, yes, it seems that all properties are automatically added to the url. In the case of dash related properties, this is of course unintended. As far as i can see, the following properties are the problematic ones,

* id
* children
* setProps
* loading_state

Please let me know if you agree. You can try out the fix in the (0.0.23rc2) release,

https://pypi.org/project/dash-leaflet/0.0.23rc2/

**Comment by Hootie9lives** [comment]
Excellent work @emilhe

**Comment by emilhe** [comment]
Thanks!
