### ISSUE TITLE
How to add popup and marker information to GeoJSON module

### ISSUE THREAD

**Issue by christianwengert** [thedirtyfew/dash-leaflet#37]
I tried to figure it out by myself but I am a bit blocked switching to dash-leaflet==0.1.0.

I had a markergroup as:

```
group = dl.MarkerClusterGroup(id="markers",
                                         children=markers,
                                          options={"polygonOptions": {"color": "red"}}
                                          ),
```

and used it 

```
 dl.Map(preferCanvas=True,
                   attributionControl=False,
                   children=[ group, ...

```

However the MarkerClusterGroup seems deprecated in favor of the SuperCluster / GeoJSON.

I managed to get markers on the SuperCluster, but how do I pass the popup with it?

**Comment by christianwengert** [comment]
A marker being like 
```
dl.Marker(children=dl.Popup(
                [
                    html.Div(f'Point {i}'),
                    html.A('link', target='_blank', href='https://www.google.com'),
                    html.Div(html.Img(src='...'))
                ]), position=item["geometry"]["coordinates"], id={"point": i})
```

**Comment by christianwengert** [comment]
If I keep using MarkerClusterGroup I get the following error:
```
react@16.v1_7_0m1598376541.13.0.js:2210 Uncaught Error: Component MarkerClusterGroup not found in dash_leaflet
    at Object.resolve (dash_renderer.v1_7_0m1598376560.dev.js:39855)
    at getProps (dash_renderer.v1_7_0m1598376560.dev.js:38885)
    at persistenceMods (dash_renderer.v1_7_0m1598376560.dev.js:38990)
    at dash_renderer.v1_7_0m1598376560.dev.js:39019
    at Array.forEach (<anonymous>)
    at persistenceMods (dash_renderer.v1_7_0m1598376560.dev.js:39017)
    at dash_renderer.v1_7_0m1598376560.dev.js:39019
    at Array.forEach (<anonymous>)
    at persistenceMods (dash_renderer.v1_7_0m1598376560.dev.js:39017)
    at dash_renderer.v1_7_0m1598376560.dev.js:39019
```

**Comment by emilhe** [comment]
The `MarkerClusterGroup` is deprecated, but my intention was actually to keep it for backwards compability. It seem that there was a mistake in the build process.

**Comment by emilhe** [comment]
Maybe the default behavior should be to bind tooltip/popup if the feature has properties with these names

**Comment by christianwengert** [comment]
Thanks @emilhe for your quick reaction all the time! 
The rc1 works again!

I am still a bit puzzled about the popups logic. In the previous version, the API was very clear as every marker could have it's own popup and the use of dash_html elements and dash_core_components as children felt very well integrated into the dash architecture as such. Currently I use images and whatnot in every popup and the code stays all readable with the MarkerCluster.

Now I have to setup a secondary dependency (transcrypt) without really seeing what this does. I understand this is done for performance reasons

> Maybe the default behavior should be to bind tooltip/popup if the feature has properties with these names?

Yes, and then it would maybe be possible to build a convert function in Python that would take a list of dl.Marker (as of now) and transforms this into geoJSON which can then be simply inserted into the GeoJSON module?

**Comment by christianwengert** [comment]
Example popup in my app

![image](https://user-images.githubusercontent.com/12936057/92231346-e3b07780-eeac-11ea-8156-7cb659405650.png)


Maybe I can help getting this functionality into the GeoJSON?

**Comment by emilhe** [comment]
It should be possible to change the dash-transctypt dependency to being optional; I'll look into that. I just tried out binding tooltip/popup per default (version 0.1.1rc2), which would lead to a syntax like this,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
import requests

import dash_leaflet.express as dlx

# Get some example data (a list of dicts with {name: country name, latlng: position tuple, ...})
marker_data = requests.get("https://gist.githubusercontent.com/erdem/8c7d26765831d0f9a8c62f02782ae00d/raw"
                           "/248037cd701af0a4957cce340dabb0fd04e38f4c/countries.json").json()
# Create marker cluster.
dicts = [dict(tooltip=m["name"], popup=m["capital"], lat=m["latlng"][0], lon=m["latlng"][1]) for m in marker_data]
cluster = dl.GeoJSON(id="markers", data=dlx.dicts_to_geojson(dicts), cluster=True, zoomToBoundsOnClick=True)
# Create app.
app = dash.Dash()
app.layout = html.Div(dl.Map([dl.TileLayer(), cluster], zoom=3, center=(51, 10)),
                      style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})

if __name__ == '__main__':
    app.run_server()
```
which is not _that_ far from the `MarkerClusterGroup` syntax.

**Comment by christianwengert** [comment]
This is already much appreciated. Syntax is pretty much back to normal +1!

But I guess we can still not use dash_html or something like that in the markers with this way

**Comment by emilhe** [comment]
Great! Yes, that's the main remaining drawback. I am still thinking about how to address that issue. I am currently thinking about something like targeting the popup container via a Dash callback somehow. If this could be done, i guess you could fill in any info needed (pictures, graph, html, ...).

**Comment by christianwengert** [comment]
> about something like targeting the popup container via a Dash callback somehow. If this could be done, i guess you could fill in any info needed (pictures, graph, html, ...).

This sounds like a good idea! I would not need more than one open popup at the time. Something along the line using pattern matching callbacks

```

@app.callback(Output({'marker': MATCH, 'target': 'popup'}, 'open'),  # a open flag could also be used in the same callback to close again if already open
              [
                Input({'marker': MATCH, 'target': 'marker'}, 'n_clicks'),
              ],
              [
                  State({'marker': MATCH, 'target': 'marker'}, 'open')
              ])
def show_popup(n):
    marker_id = ...  # some logic to extract the id from match

    return html.Div([
        html.Strong(f'Point {marker_id}'),
        html.Img(src='...')
    ])
```


Like this the GeoJSON module can stay specialized on the geojson features and if one wants to have funky popups, this is handled with "standard" dash components

**Comment by emilhe** [comment]
I have just released version 0.1.1; it fixes the MarkerClusterGroup issue, introduced the new tooltip/popup syntax, and removes the dash-transcrypt dependency :)

Yes, exactly. From a performance perspective, the idea is to avoid rendering _all_ the popups beforehand. If you have a million markers, and each tooltip contains images and graph, it would take forever to load. And from a user perspective, i would like a solution based on Dash components; as you note, it's much easier than anything else...

**Comment by christianwengert** [comment]
You're awesome! Thanks

> From a performance perspective, the idea is to avoid rendering all the popups beforehand

True. This is what I am doping now. I do not have too many markers (yet!). So getting this new way would be awesome

> And from a user perspective, i would like a solution based on Dash components; as you note, it's much easier than anything else...

Indeed, something for the next release?

**Comment by emilhe** [comment]
Now that i think about it; you can actually just use a tooltip on the `GeoJSON` component itself and update it using a callback. Hence, the following code should work without any modifications to dash-leaflet (i.e. using versiuon 0.1.1),

```
import dash
import dash_html_components as html
import dash_core_components as dcc
import dash_leaflet as dl
import plotly.express as px
import requests
import dash_leaflet.express as dlx
from dash.dependencies import Output, Input

# Get some example data (a list of dicts with {name: country name, latlng: position tuple, ...})
marker_data = requests.get("https://gist.githubusercontent.com/erdem/8c7d26765831d0f9a8c62f02782ae00d/raw"
                           "/248037cd701af0a4957cce340dabb0fd04e38f4c/countries.json").json()
# Create marker cluster.
dicts = [dict(name=m["name"], lat=m["latlng"][0], lon=m["latlng"][1]) for m in marker_data]
cluster = dl.GeoJSON(id="markers", data=dlx.dicts_to_geojson(dicts), cluster=True, zoomToBoundsOnClick=True,
                     children=[dl.Tooltip(id="tooltip")])
# Create app.
app = dash.Dash(prevent_initial_callbacks=True)
app.layout = html.Div(dl.Map([dl.TileLayer(), cluster], zoom=3, center=(51, 10)),
                      style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})


@app.callback(Output("tooltip", "children"), [Input("markers", "hover_feature")])
def update_tooltip(feature):
    if feature is None:
        return None
    # Create a figure. Or an image. Or anything else :)
    fig = px.scatter(px.data.iris(), x="sepal_width", y="sepal_length")
    fig.layout.title = feature["properties"]["name"]
    fig.layout.width = 300
    fig.layout.height = 200
    return dcc.Graph(figure=fig)


if __name__ == '__main__':
    app.run_server()
```

**Comment by christianwengert** [comment]
@emilhe Thanks for this example, not only did I get my app working with the new GeoJSON module, but I managed to throw away quite some code of which this new module now takes care! 

sent you a little thankyou through the donate button (you could maybe switch to github sponsoring instead of paypal?)

**Comment by christianwengert** [comment]
tap node on ipad foes not open the popups   is there a wirkaeound?

**Comment by emilhe** [comment]
Thanks so much! I'll definitely check out github sponsoring also - it seems that it just got out of beta. Are you using `ToolTip` or `Popup` on the iPad?

**Comment by christianwengert** [comment]
I used Popup and click_data. I would prefer Popup

**Comment by christianwengert** [comment]
If I close the popup on the x on the top right, I can open another. But if I click on another marker while a popup is open neither popup will work....

```
@app.callback(Output("popup", "children"), [Input("markers", "click_feature")])
```
with 
```
dl.GeoJSON(id="markers", data=None, cluster=True, zoomToBoundsOnClick=True,
                                 format="geojson", children=[dl.Popup(id="popup")]),
```

**Comment by christianwengert** [comment]
I believe by setting the popup options as follows
```
dl.Popup(id="popup",
autoClose=True, 
closeOnEscapeKey=True, closeOnClick=True
)
```

it is working correctly?

**Comment by christianwengert** [comment]
The problem is that the behaviour on a touch device is a bit flaky, see the example movie attached

[Untitled.mov.zip](https://github.com/thedirtyfew/dash-leaflet/files/5187517/Untitled.mov.zip)

**Comment by emilhe** [comment]
Thanks for the video! Yeah that doesn't look so good. I'll try to think about a solution. I was aware that hover functionality doesn't work on touch devices, but i would have imagined that popups would work...

**Comment by christianwengert** [comment]
Since yesterday I was testing and testing all the possible settings and it just stayed flaky on my ipad. This morning I accessed my app through a different URL and suddenly everything was fine.....

After a cleanup of the website cache on my device, the flakyness stopped. I am very sorry for the hassle caused just because some old JS or whatever was somehow interfering from the browser cache (should have known). 

Many thanks for you help and responsiveness. I guess we can close this issue

**Comment by christianwengert** [comment]
@nistran

 Here is some example code

You need a GeoJson with a dl.Popup as child:


```
dl.Map([
     dl.GeoJSON(id='markers', data=..., children=[dl.Popup(id="popup")]),
])

```

then a callbacjk in dash for filling the popup:
```
@app.callback(Output("popup", "children"),
                  [Input("markers", "click_feature")])
    def update_tooltip(feature):
        if feature is None:
            raise PreventUpdate
        image_urls = ... # get them from somewhere

        return [
            html.Div([
                'Title'
            ]),
            make_image_slider(images)
        ]
```

and the image renderer:


```
def make_image_slider(image_urls: List[str]):  # List of URLs, the output of this must be feed via callback into the dl.Popup.children
    
    images = []
    for i, url in enumerate(image_urls):
        images.append(
            html.Div(id=f'slide-{i}', children=[
                html.Img(src=url)
            ])
        )
        
    image_links = [html.A(str(i), href=f'#slide-{i}') for i, img in enumerate(images)]
    
  
    return html.Div(
        children=[
            'Title',
            ' ',
            *image_links,  
            html.Div(children=pictures, className='slides'),

        ],
        className='slider')


```


and then you need some css code for that 


```

.slider {
    width: 200px;
    text-align: center;
    overflow: hidden;
}

.slides {
    display: flex;
    overflow-x: auto;
    scroll-snap-type: x mandatory;
    scroll-behavior: smooth;
    -webkit-overflow-scrolling: touch;
}

.slides::-webkit-scrollbar {
    width: 10px;
    height: 10px;
}

.slides::-webkit-scrollbar-thumb {
    background: black;
    border-radius: 10px;
}

.slides::-webkit-scrollbar-track {
    background: transparent;
}

.slides > div {
    scroll-snap-align: start;
    flex-shrink: 0;
    width: 200px;
    height: 200px;
    margin-right: 50px;
    border-radius: 10px;
    background: #eee;
    transform-origin: center center;
    transform: scale(1);
    /*transition: transform 0.5s;*/
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 100px;
}

.slides > div:target {

    transform: scale(0.999);
}

.slider img {
    object-fit: cover;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

.slider > a {
    display: inline-flex;
    width: 1.5rem;
    height: 1.5rem;
    background: white;
    text-decoration: none;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    margin: 0 0 0.5rem 0;
    position: relative;
}

.slider > a:active {
    top: 1px;
}

```

**Comment by nistran** [comment]
> Output("popup", "children")

Thank you for that. Works like a charm. Really nice work :+1: 
I'm now wondering if there is a way to prevent the popup when using superclusters and clicking of one of the clusters. Or getting the the Points, which are included in the cluster. 
But I think this is worth a new issue ;)
