### ISSUE TITLE
GeoJson click_feature not properly working on desktop safari

### ISSUE THREAD

**Issue by christianwengert** [thedirtyfew/dash-leaflet#39]
If you click on a marker in a GeoJSON the click_feature does not trigger on Desktop Safari. However, if you click for longer than >1s (longclick?) the Input will trigger.

On mobile Safari (Iphone and Ipad) it works....

\rant whats wrong with you apple? \rant

**Comment by emilhe** [comment]
Argh, that's not so nice. I don't have a Mac, so i don't think i will be able to help with this issue :/

**Comment by r-chris** [comment]
It would not be inconceivable to build a basic GitHub Actions test for this. It won't help in fixing this one, but it will help to see where things are working and where they are not. [GitHub Actions can run on macOS](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on) as well as Windows and Ubuntu. We could probably help with building a basic selenium based (or similar) testing pipeline, which can then be executed on different OS / Browser combinations. If you are not a big fan of [Selenium](http://selenium-python.readthedocs.io), we have also been working with [TestCafe](https://devexpress.github.io/testcafe/). One could also go for one of the many browser testing frameworks (e.g. CrossBrowserTesting or similar) - some of which offer free services for OpenSource projects. What do you think @emilhe ?

**Comment by emilhe** [comment]
Building a test pipeline is in fact on my "roadmap". I haven't started on the tests yet (so far, i have been focusing on adding features), but am planning to use the same testing setup as for dash core components (which is based on Selenium). I have worked with it briefly when i wrote tests for my download component, e.g. 

https://github.com/plotly/dash-core-components/blob/ee798128a3e9bb4c3facc7c4ccccd8e6825a84ca/tests/integration/download/test_download_file.py

It seems rather easy to use, but i haven't looked into using it with MacOS. But from your link it seems that it can be configured as part of the github action. While it does not solve this issue directly, it would definitely be a step in the right directly towards better cross compability - and better stability of the library overall.

**Comment by r-chris** [comment]
Yes, it’s certainly possible to define on which OS to run the GitHub Action and macOS / Ubuntu / Windows are the ones available through GitHub by default. (You can also run on your own hardware by installing the GitHub Runner there.)

**Comment by emilhe** [comment]
Closed due to inactivity. Please re-open if still relevant.
