### ISSUE TITLE
Click events for Markers

### ISSUE THREAD

**Issue by SimonKnorke** [thedirtyfew/dash-leaflet#4]
Hello! 

I am looking for a way to create an event when a marker on a map is clicked. Is there an "onclick" - event for leaflet marker?  I'm referring to this post

https://stackoverflow.com/questions/16927793/marker-in-leaflet-click-event

My goal is to create a click reaction for a certain LayerGroup (except the popup window).
This callback should then generate further outputs (e.g. a plot) depending on the clicked marker. How could I achieve this? I am thankful for any help!

**Comment by emilhe** [comment]
At the moment, events are only emitted by the map. It would be a nice addition to enable events on markers (and other objects), i might look into that at some point. If you need a quick hack, you could try matching the positions in Python,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
import numpy as np
from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate

markers = ["a", "b", "c"]
lats = np.array([56, 56, 56])
lons = np.array([10, 11, 12])
d2 = 1e-3

app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png")] +
                    [dl.Marker(position=(lats[i], lons[i]), title=lbl) for i, lbl in enumerate(markers)],
           style={'width': "100%", 'height': "100%"}, center=[56, 11], zoom=9, id="map"),
    html.Div(id="log"),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})


@app.callback(Output("log", "children"), [Input("map", "click_lat_lng")])
def marker_click(e):
    if e is None:
        raise PreventUpdate
    # Locate nearest marker.
    lat, lon = e[0], e[1]
    r2 = (lats - lat)**2 + (lons - lon)**2
    nearest = np.argmin(r2)
    # Trigger event if the click was close enough.
    if r2[nearest] < d2:
        return "You clicked marker {}".format(markers[nearest])
    return "You clicked nothing"


if __name__ == '__main__':
    app.run_server(debug=False)
```

This approach is far from perfect, though. The "right tolerance", i.e. the `d2` depends on the zoom level.

**Comment by SimonKnorke** [comment]
Thanks @emilhe for the answer and code example, interesting approach! 
However this only works when there is no marker children such as a `dl.Tooltip` or `dl.Popup` defined. 
Let's say we add to the marker

`dl.Marker(position=(lats[i], lons[i]), title=lbl, children=[dl.Tooltip(f'Tooltip {lbl}')])` .

It seems that as long as the tooltip is open (similar to a `dl.Popup`), we cannot trigger a click event on the map. So we would have to recognize exactly this pop-up event as trigger for our callback.

For the variant with a popup window there would be one option that requires one click more:
By adding a `dcc.Button()` to each marker popup, you could trigger events directly from these markers when you click the button.
But of course that gets pretty chaotic when you have a lot of markers and you have to generate a lot of callbacks...

**Comment by emilhe** [comment]
I have added a click event to the Marker object and pushed the new code to pypi. The event should be available, if you update to version [0.0.4](https://pypi.org/project/dash-leaflet/). Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input

markers = ["a", "b", "c"]
lats = [56, 56, 56]
lons = [10, 11, 12]

app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png")] +
                    [dl.Marker(id=lbl, position=(lats[i], lons[i]), title=lbl) for i, lbl in enumerate(markers)],
           style={'width': "100%", 'height': "100%"}, center=[56, 11], zoom=9, id="map"),
    html.Div(id="log"),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})


@app.callback(Output("log", "children"), [Input(marker, "click_lat_lng") for marker in markers])
def marker_click(*args):
    if not any(list(args)):
        return ""
    marker_id = dash.callback_context.triggered[0]['prop_id'].split(".")[0]
    return "You clicked marker {}".format(marker_id)


if __name__ == '__main__':
    app.run_server(debug=False)
```

Let me know, if it works as intended.

**Comment by SimonKnorke** [comment]
Wow awesome, very well done! 
Your example worked for me! I will inform you if I encounter problems with my application.

**Comment by emilhe** [comment]
Thanks! Good to hear that it works :)
