### ISSUE TITLE
Marker Cluster Example on Heroku

### ISSUE THREAD

**Issue by marcelzar** [thedirtyfew/dash-leaflet#40]
Hi Guys,
Earlier this week I found an Example for the Marker cluster on Heroku and I copied parts to use it in a Project. Unfortunately my server crashed before I pushed this Part of Code and I have No backup. Furthemore it seemed that you changed the Marker Cluster Example on Heroku to an Example where the geoJSON Plugin is used.
Could you send/share the initial Marker Cluster Example please with me?

It was something Like:

marker_data = requests('...')

markers = [dl...(dl...(Item[...]), Position=Item['latlon'] for Item in marker_data]

cluster = dl.markerGroup(?)(id='...', children= markers,...)

Thanks in advance.

**Comment by emilhe** [comment]
Hi,

I have discontinued the `MarkerClusterGroup` component (i guess this is the one you are talking about?) in favor of the `GeoJSON` component due to performance issue with the former. I have added a [new example](http://dash-leaflet.herokuapp.com/#super_cluster). But for reference, here is the old example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
import requests

# Get some example data (a list of dicts with {name: country name, latlng: position tuple, ...})
marker_data = requests.get("https://gist.githubusercontent.com/erdem/8c7d26765831d0f9a8c62f02782ae00d/raw"
                           "/248037cd701af0a4957cce340dabb0fd04e38f4c/countries.json").json()
# Create marker cluster.
markers = [dl.Marker(children=dl.Tooltip(item["name"]), position=item["latlng"]) for item in marker_data]
cluster = dl.MarkerClusterGroup(id="markers", children=markers, options={"polygonOptions": {"color": "red"}})
# Create app.
app = dash.Dash()
app.layout = html.Div(dl.Map([dl.TileLayer(), cluster], zoom=3, center=(51, 10)),
                      style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})

if __name__ == '__main__':
    app.run_server()

```

**Comment by marcelzar** [comment]
Yes  exactly, thank you very much 👍
