### ISSUE TITLE
REQUEST: geo-search control and GeotiffOverlay usage

### ISSUE THREAD

**Issue by ougx** [thedirtyfew/dash-leaflet#43]
Great package largely extend the capability of Dash for spatial projects. Can you add 1) geosearch tool https://github.com/smeijer/leaflet-geosearch 2) show example of `GeotiffOverlay`? Especailly can we construct the tiff from `ndarray` and plot it?

Thanks!

**Comment by meteoDaniel** [comment]
I am also interested in such a feature. 
Another python implementation can be found her: 
https://ipyleaflet.readthedocs.io/en/latest/api_reference/search_control.html#example

For me the most important requirement is to get the coordinate of the search result.

**Comment by emilhe** [comment]
@meteoDaniel - Wow, that's some pretty comprehensive Python bindings for Leaflet! I wasn't aware that it existed.

**Comment by meteoDaniel** [comment]
@emilhe I am working with leaflet + python for 2 years now and found that repo a few days ago and I was really impressed. I knew folium and jinja+html to work with leaflet in python. 
Nevertheless ipyleaflet is not able to interact with dash so running a server with a map application is hard to obtain.

**Comment by sina7272** [comment]
Hi guys, 

I have a Raster file (geotiff) and I want to show it on the dash leaflet map. I am using the below code but it does not work, any idea how I can show this geotiff file on my dash leaflet?? Thanks

` 
import dash
import dash_leaflet as dl

app = dash.Dash()

def Raster_N():

    raster = dl.GeoTIFFOverlay(id="GEOTIFF_ID", interactive=True, url="/assets/Raster_main.tiff", band=1, opacity=1)
    return raster

Raster = Raster_N()

app.layout = dl.Map([dl.TileLayer(), Raster], style={'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server(debug = True)
`

**Comment by lggutierrez** [comment]
Hi @sina7272. I am having the same issue. My GeoTiffs are not showing up with the GeoTIFFOverlay approach. I also tried using the Terracotta-Dash example but didn't have luck with that one. Where you able to find a solution for this?

**Comment by Ma-Schw** [comment]
Hi @lggutierrez, I have been struggling a bit with the GeoTIFFOverlay as well in the last days. What I did not get until just now was how to define the colors and classes to be displayed. As long as I did not get it right, my raster cells were not showing. What works for me is this:

`
color_domain = dict(domainMin=0, domainMax=160183, 
                    classes = [0, 5000, 100000, 160183], 
                    colorscale = ['red', 'green', 'blue']

dl.GeoTIFFOverlay(id='GEOTIFF_ID', interactive=True, url="/assets/myfile.tif", band=0, opacity=0.9, **color_domain),
)
`

If I dont set domainMin and domainMax only rasters with the value 0 were showing. Maybe this is of help to you.

Also it is important to use WGS1984 as coordinate reference system.

**Comment by emilhe** [comment]
@Ma-Schw that is correct. Those properties must be set (to define the color scale), and the projection must be WGS1984 (otherwise, the result will be wrong; no reprojection is performed). Finally, it should be noted that the _whole_ raster is added to the map. Hence, this method is not suited for large amounts of data, instead I would recommend loading the data via tiles,

https://github.com/thedirtyfew/terracotta-dash-example

**Comment by lggutierrez** [comment]
@Ma-Schw thank you for the suggestion! I was missing that part. I was able to get it working now. 

@emilhe I did try to run the terracotta-dash-example, but I am getting an ImportError:

from terracotta.server.flask_api import convert_exceptions
ImportError: cannot import name 'convert_exceptions' from 'terracotta.server.flask_api'

I read a comment on the Issues tab of that repo recommending the that line, which doesn't sound like a good idea to me. I think I have an issue with package versions. Do you have any suggestions on the specific requirement versions to run that example? Unless I am missing something, the requirement file on that repo doesn't specify versions. 

PS 1: I can submit an issue on that repo if that would be cleaner
PS 2: Thank you for putting this together; these tools are pretty helpful!

**Comment by emilhe** [comment]
Closed due to inactivity. Please re-open if still relevant.
