### ISSUE TITLE
ERROR regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by verstraetejonas** [thedirtyfew/dash-leaflet#44]
Thanks for this great package. When using geojson I got an error 'regeneratorRuntime is not defined'. 
According to https://github.com/babel/babel/issues/9849#issuecomment-487040428 it could be fixed by importing regeneratorRuntime from "regenerator-runtime".

**Comment by emilhe** [comment]
Thanks! What version are you on?

**Comment by verstraetejonas** [comment]
version 0.1.3

**Comment by emilhe** [comment]
Could you post an MWE? The documentation,

http://dash-leaflet.herokuapp.com/

Is running with 0.1.3 also (and Dash 1.16.0), and there i don't see the error.

**Comment by wolfiex** [comment]
What was the found solution to this?

Mac OS 
python 3.8.5
Opera
dash leaflet 0.1.13

**Comment by wolfiex** [comment]
It seems it may possibly be a version with dash itself. 
https://github.com/plotly/dash/issues/1087
