### ISSUE TITLE
Freehand Drawing / Selection

### ISSUE THREAD

**Issue by Robbie-Palmer** [thedirtyfew/dash-leaflet#45]
I would love to be able to enable free-hand drawing of polygons / selection of regions
Examples are the [closed freeform annotation tool in plotly images](https://plotly.com/python/images/) and [plotly's lasso selection](https://plotly.com/javascript/lasso-selection/)

The [FreeDraw plugin](https://github.com/Wildhoney/Leaflet.FreeDraw) looks pretty light-weight and triggers an event when the drawing has completed

If its events could be connected to a Dash callback, the Dash app could then draw a suitable Polygon without making this an explicit feature in Dash-Leaflet, or use the region for geospatial queries such as counting the number of markers inside the selected region (without overlaying a visual polygon on the map)

Here's an example in JavaScript where the event is captured to draw a Polygon (though in this example editing creates new polygons instead of replacing the previous one)

```
const LAT_LNG = [51.505, -0.09];
const TILE_URL = 'https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png';

const map = new L.Map(document.querySelector('section.map'), { doubleClickZoom: false }).setView(LAT_LNG, 14);
L.tileLayer(TILE_URL).addTo(map);
const freeDraw = new FreeDraw({ mode: FreeDraw.ALL });
freeDraw.on('markers', event => {
    L.polygon(event.latLngs, {color: 'red'}).addTo(map);
});
map.addLayer(freeDraw);
```

And on JS-Fiddle with the CSS
https://jsfiddle.net/5oacexuf/1/

**Comment by emilhe** [comment]
It looks pretty cool! In some aspects similar to [geoman](https://github.com/geoman-io/leaflet-geoman), but obviously more light-weight. There is also a react wrapper to build on,

https://github.com/elangobharathi/react-leaflet-freedraw

so the leaflet part of implementation will probably not be too problematic. I think the hardest part for this kind of component would be designing the Dash API (:

**Comment by emilhe** [comment]
As a starting point, could you outline your intended use case? 🙃

**Comment by Robbie-Palmer** [comment]
Currently users draw a polygon by clicking their mouse for each sequential point of the polygon exterior, and each of these will be connected by a straight line.
I would like to enable users to click and hold, while dragging their mouse to create a polygon. This enables finer control over the polygon shape, with smooth edges fully under their control and can be faster than many clicks for complex shapes.

The main use case would be to visualise this polygon on the map, and is just an alternative to the clicking mechanism for creating a polygon.
Given a polygon is visualised on the map the user may then use other features of the dash app to extract pixel data from within that polygon for analysis, or to count the number of markers in that region etc.
Another use case is where that polygon is used exclusively for counting the number of markers in that region etc without publishing the polygon for visualisation (aka lasso selection versus drawing freehand polygons)

I would also like the users to be able to edit the polygons that are published like the edit functionality available in freedraw.
Would need to take this mode into account in the callbacks unlike in that JS example I gave where editing leaves the initial polygon and just overlays a new version!

Geoman does look cool, but it only allows the shapes based on clicks rather than dragging.
The snipping functionality in geoman is something I would like to implement, but that can all be done in Python, given an initial shape, and given this mode is chosen and defines a new shape, python libraries such as shapely can be used to take the difference and update the initial annotation.

**Comment by emilhe** [comment]
After having looked at the library a little closer, i have noticed that the bundle size is actually pretty large (~600 kB). Including `FreeDraw` would thus increase the bundle size of Dash Leaflet by almost 100%, which is a lot.

**Comment by emilhe** [comment]
I just made an initial implementation. You can try it here,

https://pypi.org/project/dash-leaflet/0.1.4rc2/

A basic example would be,

```
import json
import dash
import dash_html_components as html
import dash_core_components as dcc
import dash_leaflet as dl

from dash.dependencies import Input, Output

modes = ["ALL", "CREATE", "EDIT", "DELETE", "APPEND"]
# Create app.
app = dash.Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dl.Map([dl.TileLayer(), dl.Freedraw(modes=[modes[0]], id="freedraw")], zoom=3, center=(51, 10)),
    dcc.Dropdown(id="dd", options=[dict(value=m, label=m) for m in modes], value=modes[0], multi=True),
    html.Div(id="output")
], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})


@app.callback(Output("freedraw", "modes"), [Input("dd", "value")])
def update(modes):
    return [modes] if isinstance(modes, str) else modes


@app.callback(Output("output", "children"), [Input("freedraw", "markers")])
def listen(markers):
    return json.dumps(markers)


if __name__ == '__main__':
    app.run_server(port=5757, debug=True)
```
And here is the CSS from the previous example,
```
body,
html {
  overflow: hidden;
}

a {
  color: dodgerblue;
}

.leaflet-container {
  height: 400px;
  width: 90%;
  margin: 0 auto;
}

path.leaflet-line {
  stroke: #50622b;
  stroke-width: 2;
}

div.leaflet-edge {
  background-color: #95bc59;
  box-shadow: 0 0 0 2px white, 0 0 10px rgba(0, 0, 0, 0.35);
  border-radius: 50%;
  cursor: move;
  outline: none;
  transition: background-color 0.25s;
}

div.leaflet-edge.disabled {
  pointer-events: none;
  background-color: #bbb;
}

path.leaflet-polygon {
  fill: #b4cd8a;
  stroke: #50622b;
  stroke-width: 2;
  fill-opacity: 0.75;
}

.map.mode-create {
  cursor: crosshair;
}
```

**Comment by Robbie-Palmer** [comment]
You have no idea how happy this has made me :partying_face: :champagne:
I yelled with excitement haha it's so beautiful, thank-you!

Is it possible to fully control the rendering of the polygons server-side?
The markers property contains a list of polygons with all their coordinates, so I was thinking this could be used to draw on the map using Dash leaflet's Polygon class or GeoJSON component, enabling control over styling like weight, colour, hover-style etc.

By using callbacks to link the Polygons or GeoJSON components to the polygons managed by FreeDraw, this would provide full on editing ability of any Polygon or GeoJSON component.
Would also be able to move polygons from `editable` to `published` state by adding or removing it from the FreeDraw layer but keeping the corresponding Polygon or GeoJSON.
FreeDraw's [Bundled Methods](https://github.com/Wildhoney/Leaflet.FreeDraw#bundled-methods) would be required to link these components to enable that, through `create`, `remove`, `clear` etc.

Aka FreeDraw would have no responsibility for rendering anything on the map, its sole responsibility would be as storage of the current state of any drawable / editable polygons, and as the computation engine for taking the drag events, and determining the coordinates of a corresponding polygon. Then its up to the dash app developer to link this to the additional control mechanisms and visualisations.

Will the package size be a big concern? If so perhaps this could be pulled into another repo and treated as an optional Dash-Leaflet plugin
Depends on how you balance trade-offs between having everything in one place vs smaller package size, and whether you view this functionality as valuable enough to be core

**Comment by emilhe** [comment]
You can control the polygon rendering via the CSS classes used by [FreeDraw](https://github.com/Wildhoney/Leaflet.FreeDraw). Does that answer you question?

It should be straight forward to convert the `markers` into `GeoJSON` or `Polygon` with the current interface. But you are right, that in order to be able to "load" e.g. a GeoJSON to edit it, a different interface is needed.  

In terms of size, it's too large that i would include it as-is. The "standard" advice is that a package should not exceed 244 kB. Presently, dash-leaflet is already > 600 kB. And FreeDraw would add another 600 kB. Hence, it should either be some kind of optional dependency as you note, or some kind of async loading should be applied (i haven't tried that before, but i guess i should be doable).

**Comment by Robbie-Palmer** [comment]
Ah yes sorry I hadn't paid proper attention to the CSS
By setting the polygon `stroke-width` and `fill-opacity` to 0 I can have invisible FreeDraw polygons and would be able just render the corresponding Dash-Leaflet Polygon or GeoJSON
Would lose some nice interactions though such as the fluid editing since the dash callback would only trigger once the mouse button was released. But possibly some half-way house stuff could be done here like setting `stroke-width` to 1 giving draggable wire-frame around the polygon for some level of interactivity.

I'm guessing to be able to directly use the FreeDraw Polygons and dynamically change their style via the Dash callbacks I would need to create Dash components for the FreeDraw lines, edges and polygons, similar to the current Dash-Leaflet components or dash-core components?
If I could directly reference the FreeDraw Polygons to set its own colour, hover-style and detect clicks then that would cover my needs without holding on to a matching `Polygon` or `GeoJSON` component

I think the bundled methods would be an important part of the API, beyond ability to edit loaded shapes
Being able to clear all polygons is important, in cases such as allowing a user to click a clear button rather than individually deleting polygons, or because the server knows the map has changed and they no longer apply
I think the `create` function would be required for persisting the drawings on refresh, so the polygons could be re-applied

I'm hitting the issue of not being able to clear the drawings when the map has changed at the moment
I removed the `Freedraw` layer from the map but the polygons remain
I tried setting the `markers` property via a callback but that didn't work either

**Comment by Lkruitwagen** [comment]
This is really awesome. I might have missed something, but is there support for vanilla [leaflet draw](https://jsfiddle.net/user2314737/324h2d9q/)?

**Comment by emilhe** [comment]
I haven't implemented it, but I would be happy to review a pull request :)

**Comment by Lkruitwagen** [comment]
Hmm okay I might give this a go. Currently running around with `click_lat_lng` callbacks into `dl.Polyline`. Would be awesome if there the leaflet `drawControl` was available! Will check it out.

**Comment by prl900** [comment]
I'm wondering if there are any recent updates about this drawing functionality. 

The polygon drawing functionality is something I'd like to add to my app but following the discussion, it's not clear to me what is the recommended way to go, either using the FreeDraw example from @emilhe or porting @Lkruitwagen leaflet_draw.

**Comment by emilhe** [comment]
There are no updates from my side.

**Comment by Lkruitwagen** [comment]
Hi @prl900 - depends what you want to do. The FreeDraw example isn't good for drawing/editing polygons. I've been trying to get leaflet_draw working but am stuck in a maze of JS/react/dash-custom-component boilerplate. I really want to get this feature working. @emilhe now that there seems to be some demand, could we find a time to discuss this? I've emailed you recently. @prl900 would you be willing to work on this together?

**Comment by emilhe** [comment]
Hi @Lkruitwagen. Wait issues are you looking at? 

I am currently reviewing the `GeoJSON` component and its interface to Dash with focus on adding more examples and easing the process of injecting custom  javascript rendering code (via the new `assign` function in `dash-extensions`), so I haven't really gotten around to this issue. At the top of my head, a few points still need to addressed,

* Was functionality is needed? I it just drawing polygons? Or should it also be supported e.g. to select points on the map (like you can do in a plotly graph with the lasso)? Does that mean that integration with other components is needed?
* What is the right library to integrate (it sounds like you are converging towards leaflet_draw?). How should the wrapping look like (e.g. very light, just pass props, or do we need more)?
* How would these changes impact bundle size? If the library is large, a larger restructuring of dash-leaflet might be needed to allow async lazy loading

**Comment by Lkruitwagen** [comment]
Hi @emilhe, I've seen your work on `dash-extensions`, it looks great! To answer you questions briefly:

- what functionality is needed? -> In my case, and probably many others, it's to enable users to add polygon inputs to maps that can be used for downstream tasks (e.g. labelling data). I don't have need of the plotly lasso functionality (and you can probably do that with Plotly mapbox scatterplots anyway)
- Is this the right library? -> I think `leaflet-draw` is the right library to integrate. I don't know any others, but it seems to be the typical one that's used, e.g. [geojson.io](http://geojson.io).
- How should the wrapping look? -> For me, wrapping just needs to be able to get the Feature data into the dash callbacks. I'll describe below why I'm finding this difficult.
- How will this change bundle size? -> I have no idea how this would change bundle size, but `leaflet-draw` seems to be used pretty widely without issue.

And here's where I'm stuck:

`leaflet-draw`'s `drawControl` needs to be instantiated with a `FeatureLayer`, [example](https://github.com/Leaflet/Leaflet.draw/blob/d5dd11781c2e07f9e719308e504fe579000edf54/src/Leaflet.draw.js#L32).`FeatureLayer` isn't implemented in dash-leaflet yet, but this could use the `GeoJSON` component instead? But then I get lost in how to make changes to `leaflet-draw` to take either a `FeatureLayer` or `GeoJSON` as a property, and how to add or edit features using `leaflet-draw`'s events. Then the final issue is how to expose the geometries for use in dash callbacks.

Thanks!

**Comment by emilhe** [comment]
Thanks :)

Ah, you mean FeatureGroup? I think that component can be added relatively easily. I just never had the need for until - until now I guess ;)

The mapping of events into dash props on the other hand is more complicated. This is typically the point that requires some work.

**Comment by prl900** [comment]
I agree adding the possibility to draw custom polygons on a map would be very useful. In my case, it would enable users to define regions to calculate statistics posting the geojson polygon to a backend service.

Unfortunately, I have no experience with JavaScript and React so I'm not sure how much I can contribute to implementing this feature. Otherwise, I'm keen to participate in this development and learn more about the internals of dash_leaflet.

**Comment by emilhe** [comment]
I have just pushed a new version of dash-leaflet (0.1.15) which includes the `FeatureGroup` component that you requested @Lkruitwagen.

**Comment by Lkruitwagen** [comment]
Sorry, `FeatureGroup`, yes! Thanks for the push. Do you know of any examples where one React component is instantiated with another as a target? I'm thinking of e.g. [dbc tooltip](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/tooltip/) where you have to specify a target. Perhaps we could do that with the `DrawControl` component, where it's given a `FeatureGroup` as a target?

I'll try to take another look at this this week, I've written to some JS colleagues who might be able to help.

**Comment by emilhe** [comment]
I have just taken a stab at implementing leaflet draw. I have implemented an `EditControl` component and linked the CSS as part of dash-leaflet. The bundle increase is noticeable (a little more than 100 kB), but not extreme.

I have mapped all action type of events (e.g. when draw starts/ends, edit starts/ends, ...) to an `action` property, the create event to a `create_feature` property, the edit event to an `edit_features` property and the delete event to a `delete_features` property. The remaining events are just kept "raw" for the advanced user (their usage thus require writing javascript since they are functional props). Here is a small example that prints all actions and create, edit and delete operation below the map,

```
import json
import dash_html_components as html
import dash_leaflet as dl
from dash import Dash
from dash.dependencies import Output, Input

# What prop changes to log.
event_types = ["action", "create_feature", "edit_features", "delete_features"]
# Create example app.
app = Dash()
app.layout = html.Div([
    dl.Map(center=[56, 10], zoom=4, children=[
        dl.TileLayer(), dl.FeatureGroup([dl.EditControl(id="edit_control")])
    ], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}, id="map")] +
    [html.Div([html.Div(f"Last [{event_type}]:"), html.Div(id=event_type)]) for event_type in event_types],
)
# Bind callbacks.
for event_type in event_types:
    app.callback(Output(event_type, "children"), Input("edit_control", event_type))(lambda x: json.dumps(x))

if __name__ == '__main__':
    app.run_server(port=7780)
```

it should work with the `dash-leaflet==0.0.16rc1` prerelease.

**Comment by Lkruitwagen** [comment]
@emilhe this is **awesome**, thanks so much for digging in to this. I'm looking at the react components ([e.g. here](https://github.com/thedirtyfew/dash-leaflet/blob/leaflet-draw/src/lib/components/EditControl.react.js)) but can't see where the action properties are mapped?

Is there a prop for getting the features out of the `FeatureGroup`? I can do something like this with a `dcc.Store`, but is there an easier way?

Anyway, thanks so much for this, bunch of coffees coming your way! 

```
import json
import dash_html_components as html
import dash_core_components as dcc
import dash_leaflet as dl
from dash import Dash
from dash.dependencies import Output, Input, State

# What prop changes to log.
event_types = ["action", "create_feature", "edit_features", "delete_features"]
# Create example app.
app = Dash()
app.layout = html.Div([
    dl.Map(center=[56, 10], zoom=4, children=[
        dl.TileLayer(), dl.FeatureGroup(id='my_fc',children=[dl.EditControl(id="edit_control")])
    ], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}, id="map")] +
    [
        html.Div([
            html.Div(f"Last [{event_type}]:"), 
            html.Div(id=event_type)]) 
        for event_type in event_types
    ] + 
    [
        html.Hr(),
        html.Div([
            html.Div("FeatureGroup State:"),
            html.Div(id='featuregroup_state'),
        ]),
        dcc.Store(id='featuregroup_store', data={}),
    ],
)
# Bind callbacks.
for event_type in event_types:
    app.callback(Output(event_type, "children"), Input("edit_control", event_type))(lambda x: json.dumps(x))

@app.callback(Output('featuregroup_state','children'),Input('featuregroup_store','data'))
def fg_state(data):
    return json.dumps(data)

@app.callback(
    Output('featuregroup_store','data'),
    [Input('edit_control','create_feature'),Input('edit_control','edit_features'),Input('edit_control','delete_features')],
    [State('featuregroup_store','data')])
def update_featuregroup_store(create_action, edit_action, delete_action, data):
    if create_action:
        # create action -> add key:value to store data 
        data[create_action['_leaflet_id']] = json.dumps(create_action)
        return data
    elif edit_action:
        # edit action -> update dict keys
        data.update(json.dumps(edit_action))
        return data
    elif delete_action:
        # delete action -> delete dict data by key
        for kk in json.dumps(delete_action).keys():
            del data[kk]
        return data
    else:
        return data

if __name__ == '__main__':
    app.run_server(port=7780)
```

**Comment by prl900** [comment]
Wow, this is great! Thank you very much @emilhe for implementing this functionality. I'm so happy I can now make my apps even more interactive using this feature. It opens so many options. I'm going to chip in a donation to the project.

**Comment by emilhe** [comment]
Thanks! @Lkruitwagen the properties are mapped [here](https://github.com/thedirtyfew/dash-leaflet/blob/9117fa04d5ddc26b38d0d627d051d5c6bddaa412/src/lib/components/EditControl.react.js#L46). 

Leaflet itself works with layers, not react objects. You can think about the react objects coming from Dash to dash-leaflet as "instructions on what to draw". The control creates layers directly (i.e. without creating react object), so it is not possible to get "the features out of the feature group" (as they don't exists as react objects).

With the current implementation, the `update_featuregroup_store` is what you would do if you needed to collect all features in the Dash layer. If that is the most common use case, it might make more sense to implement this functionality in the `EditControl` directly, either instead of the current props (create_feature, edit_features, ..) or in addition to them. That kind of what i mean by a thin wrapper (just mapping events, like it is done with `onMounted`) versus a not-so-thin wrapper (capturing events and mapping them into a data structure representing what-is-on-the-screen-now).

**Comment by Lkruitwagen** [comment]
Hi @emilhe, amazing, thanks for the explanation. 

I think getting user-drawn features for a backend process like @prl900 has described is a very common use case. I image we'd want them to come through as GeoJSON? From your explanation, however, I can see how this would get complicated, and it's (almost) trivial to implement this in Python with something like dcc.Store. (I say *almost* because there's a small difference between supported shapes between Leaflet and GeoJSON: GeoJSON can't support circles, so you'd need to make some decision about the number of vertices a Leaflet circle should have when converted to GeoJSON.)

I've made a gist showing this [here](https://gist.github.com/Lkruitwagen/dbe9d9f23dc2c3a32dc00ffeb62b1cc0). I think it's totally functional as is, but up to you if you want to make it a bit more accessible! Again, thank you so much!

**Comment by emilhe** [comment]
Inspired by you gist @Lkruitwagen, have done another take where the ["create_feature", "edit_features", "delete_features"] properties are replaced by a single `geojson` property that holds the all geometries currently shown as geojson. While it did require some more work, after playing around a bit with it, I feel that this syntax is much more Dash like. And since geojson is a standard format, I think this implementation will make it much easier for people to use the geometries with few lines of code. In the new syntax, mirroring the edit layer for example is pretty easily, 

```
import json
import dash_html_components as html
import dash_leaflet as dl
from dash import Dash
from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate
from dash_extensions.javascript import assign

# How to render geojson.
point_to_layer = assign("""function(feature, latlng, context){
    const p = feature.properties;
    if(p.type === 'circlemarker'){return L.circleMarker(latlng, radius=p._radius)}
    if(p.type === 'circle'){return L.circle(latlng, radius=p._mRadius)}
    return L.marker(latlng);
}""")
# Create example app.
app = Dash()
app.layout = html.Div([
    dl.Map(center=[56, 10], zoom=4, children=[
        dl.TileLayer(), dl.FeatureGroup([dl.EditControl(id="edit_control"),
                                         dl.Marker(position=[56, 10])],
                                        ),
    ], style={'width': '100%', 'height': '45vh', 'margin': "auto", "display": "block"}, id="map"),
    html.Div([html.Div(f"Last ACTION invoked:"), html.Div(id="action")]),
    dl.Map(center=[56, 10], zoom=4, children=[
        dl.TileLayer(), dl.GeoJSON(id="geojson", options=dict(pointToLayer=point_to_layer)),
    ], style={'width': '100%', 'height': '45vh', 'margin': "auto", "display": "block"}, id="mirror"),
])


@app.callback(Output("action", "children"), Input("edit_control", "action"))
def action(x):
    return json.dumps(x)


@app.callback(Output("geojson", "data"), Input("edit_control", "geojson"))
def features(x):
    if not x:
        raise PreventUpdate
    print(x)
    return x


if __name__ == '__main__':
    app.run_server(port=7781)
```

You can try it out with new `0.1.16rc2` prerelease.

**Comment by prl900** [comment]
Awesome! I have been testing this and is exactly what I need, thanks for this @emilhe. I think it integrates well with the Dash style and is easy enough to include the toolbar and get the polygons that users draw.

Just one question about configuring the functionality included in the drawing toolbar. Is it possible to limit the options that are shown? The circle option is not usually required in most of the use-cases I work with. in `leaflet-draw` the options to disable toolbar options are available [here](https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html). I wonder if this is also possible in dash-leaflet.

**Comment by emilhe** [comment]
Great, thanks for the feedback @prl900 . Yes, you can pass options along to the leaflet component via the `draw` and `edit` props,

```
...
dl.EditControl(id="edit_control", draw=dict(circle=False))
...
```

**Comment by emilhe** [comment]
The feature has been incorporated in the `dash-leaflet==0.1.16` release.

**Comment by Robbie-Palmer** [comment]
@emilhe thank-you very much for this
I believe dash-leaflet did already somewhat had point annotation and polygon annotation functionality which was demonstrated in the docs (or maybe it was in a GitHub issue, I can't see it now)

I implemented this functionality by created a `dash_bootstrap_components` `RadioItems` object to choose between points or polygons & by capturing the `click_lat_lng`
Then if it was a point, adding a `CircleMarker` to a layer on the map
If the chosen tool was a Polygon, then appending map clicks to a `PolyLine`, and following clicking on the original point, return a `Polygon`

Having `leaflet-draw` is so much more powerful than this, given the editing additional drawing types already implemented (and with the above approach, it was very hard for a user to close a polygon, as was hard to actually click right on the original point)

I would still like to have a `Freehand Drawing` feature request open
The clicking of each individual point to construct a polygon can be very burdensome for intricate use cases
The use case being wanting to draw a detailed polygon, simply by clicking and holding the mouse click button and tracing the region vs currently requiring to click along fine edges
`leaflet-draw` unfortunately doesn't have this feature which is why I pointed to `FreeDraw` in the original issue, as this feature was more important to me than editing etc

I don't believe there should be a need for a difference in Drawing vs Selection e.g. drawing polygon vs lasso as long as can have control over whether the annotation is visible or not, as in both cases it is generating GeoJson that gets sent back to a callback, in one case the response will be to render, in the other, a geospatial query will be carried out
But if there is a difference required in implementation, the former is much more important to my use cases

In terms of this being the correct library vs plotly mapbox, I require the `SimpleCRS` only provided in `Leaflet`

Shall I open this in a separate issue given the discussion in this issue became about more general powerful annotation tooling rather than the specific Freehand polygon tool?

(This feature has fell into the background in my company for the past year, but is being revived now, I hope I'll be able to get focus on this to either provide development for it or to provide funding to this project :relaxed:

**Comment by emilhe** [comment]
@Robbie-Palmer Ah, yes, I closed the issue as my take away from the discussion was that the `EditControl` was fulfilling the needs that initiated this issue. I think a new issue with clear focus on the `FreeDraw ` component would be good :)
