### ISSUE TITLE
How to control tooltip default options

### ISSUE THREAD

**Issue by nistran** [thedirtyfew/dash-leaflet#49]
Hi there.

Currently I'm working with tooltips to show pictures on hover. Now I run into the problem, that the tooltips have opacity = 0.9 by default (see https://github.com/Leaflet/Leaflet/blob/5b30f7d34461a5bca7927ff368547abe516a8de8/src/layer/Tooltip.js#L66). Is there a way to control the layers default options? In my case I need to control them for the tooltip-pane. 
Thanks in advance.

**Comment by nistran** [comment]
Ok I interpreted this wrong somehow. In fact it is the default parameter of the tooltip itself. 
So I know I'm able to bind a new tooltip on leaflet but I already tested this with popups and the solution is not so smooth as it is using the default popup.

**Comment by emilhe** [comment]
Could you clarify the issue/question? Maybe with an example of what is working/what is not?

**Comment by nistran** [comment]
Finally I solved it. If someone comes across the same problem here is the solution. I solved it with binding my own JavaScript function on the onEachFeature function in the GeoJSON module. 
My function has the following code:

`window.dash_props = Object.assign({}, window.dash_props, {
    module: {
        on_each_feature: function(feature, layer, context) {
            if (!feature.properties) {
                return
            }
            if (feature.properties.popup) {
                layer.bindPopup(feature.properties.popup)
            }
            if (feature.properties.tooltip) {
                layer.bindTooltip(feature.properties.tooltip, { opacity: 1.0 })
            }
        }
    }
});`

**Comment by nistran** [comment]
> Could you clarify the issue/question? Maybe with an example of what is working/what is not?

I renamed the issue topic. Hopefully it is now clearer what my issue was.
