### ISSUE TITLE
Support for onClick event on Markers or Layer

### ISSUE THREAD

**Issue by acoque** [thedirtyfew/dash-leaflet#5]
Hi,

What a nice work you've done ! That's just what I was looking for since the current Plotly's Scattermapbox has no bounds argument / fitBounds method (and my function to get a zoom value from a given bounding box wasn't fancy enough since it didn't handle browser window resizing...).

I need to retrieve the id of the marker I clicked on and I didn't find a nice way to do it. With Plotly's Scattermapbox I used the *clickData* callback property but it works only on dcc.Graph objects, not dl.Map ones.
Would you consider implementing  *onClick* event (and not only [*dbl_*]*click_lat_lng*) as a Dash callback property (either for the Map or the Marker object) ? Or maybe I missed an already implemented feature (or you got a better idea) :thinking: 

Thanks ;)

**Comment by emilhe** [comment]
Thanks! In fact, I just implemented an onclick event for the Marker object this morning. It should be available in the latest version ([0.0.4](https://pypi.org/project/dash-leaflet/)). Here is a small example,
```
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input

markers = ["a", "b", "c"]
lats = [56, 56, 56]
lons = [10, 11, 12]

app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png")] +
                    [dl.Marker(id=lbl, position=(lats[i], lons[i]), title=lbl) for i, lbl in enumerate(markers)],
           style={'width': "100%", 'height': "100%"}, center=[56, 11], zoom=9, id="map"),
    html.Div(id="log"),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})


@app.callback(Output("log", "children"), [Input(marker, "click_lat_lng") for marker in markers])
def marker_click(*args):
    if not any(list(args)):
        return ""
    marker_id = dash.callback_context.triggered[0]['prop_id'].split(".")[0]
    return "You clicked marker {}".format(marker_id)


if __name__ == '__main__':
    app.run_server(debug=False)
```
Does it fit your usecase?

**Comment by acoque** [comment]
Oh, cool ! I like this kind of coincidence ;)

Unfortunately, even if it's kind of what I asked for (onclick event for the Marker object), it does not fit my usecase. I guess my request wasn't particularly clear (my bad, I should have shown a code snippet...). Therefore, I would understand if you would like to close this ticket.

This is what I used in combination with a Plotly's Scattermapbox contained in a dcc.Graph :
```Python
@dashapp.callback(Output('point-data-signal', 'children'),
                  [Input('campaign-data-signal', 'children'), Input('dropdown-point', 'value'),
                   Input('map', 'clickData')],	# 'map' is the id of the dcc.Graph object containing the go.Scattermapbox object
                  [State('radio-campaign', 'value')])
def update_point_data(value, selected_points, clickData, campaign_id):
    if value is None:
        raise PreventUpdate
    else:
        ctx = dash.callback_context
        if ctx.triggered:
            prop_id = ctx.triggered[0]['prop_id'].split('.')[0]
            if prop_id == 'campaign-data-signal':
				# ~~not useful to show this part of the code~~
            else:  # i.e. prop_id == 'map'
                df_points = get_df(campaign_id + '_' + 'points')
                df_selected_points = get_df(campaign_id + '_' + 'selected_points')
                df_unselected_points = get_df(campaign_id + '_' + 'unselected_points')
                point = clickData['points'][0]['text']	    # -> the point on wich I clicked
                if point in df_selected_points.index:
                    df_selected_points.drop(point, inplace=True)
                    df_unselected_points = df_unselected_points.append(df_points.loc[point])
                else:  # i.e. point in df_unselected_points.index
                    df_unselected_points.drop(point, inplace=True)
                    df_selected_points = df_selected_points.append(df_points.loc[point])
                # store the data in a plasma in-memory object store (using pyarrow)
                client.delete([get_object_id(campaign_id + '_' + 'selected_points')])
                store_df(df_selected_points, campaign_id + '_' + 'selected_points')
                client.delete([get_object_id(campaign_id + '_' + 'unselected_points')])
                store_df(df_unselected_points, campaign_id + '_' + 'unselected_points')
        return np.random.random()

# Then I have another callback that listens to 'point-data-signal' and updates the map. I did this (i.e. not a straightforward map update) because I need to have this intermediary step for other callbacks.
```

Why I can't just use what you showed me in your example is that I can't have an external list containing markers. Indeed, the number of markers depends on which dataset (stored in an external database) the user wanna see, and since multiple users can simultaneously use the app, I can't store it as a global variable. That's why I was listening to the dcc.Graph object and not to each marker.

Do you have any idea how I should proceed to get my way or if you'll ever implement something like this clickData thing on the dl.Map object ?

Cheers

**Comment by emilhe** [comment]
I guess you could do something like this,

```
import json
import dash
import dash_html_components as html
import dash_leaflet as dl
import dash_core_components as dcc
from dash.dependencies import Output, Input, ALL

# These data could be in an external database, but i use a dict for simplicity.
data_source = {
    "Some markers": {"a": (56, 10), "b": (56, 11)},
    "Some other markers": {"c": (55, 10), "d": (55, 11)},
}
# Create app.
app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"),
                     dl.LayerGroup(id="markers")],
           style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8, id="map"),
    dcc.Dropdown(id="dd", options=[{"value": value, "label": value} for value in data_source]),
    html.Div(id="log"),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})


@app.callback(Output("markers", "children"), [Input("dd", "value")])
def update_markers(value):
    if value is None:
        return []
    data = data_source[value]
    return [dl.Marker(id={'type': 'marker', 'index': key}, position=data[key]) for key in data]


@app.callback(Output("log", "children"), [Input({'type': 'marker', 'index': ALL}, 'n_clicks')])
def marker_click(args):
    if not any(args):
        return ""
    value = dash.callback_context.triggered[0]['value']
    marker_id = json.loads(dash.callback_context.triggered[0]['prop_id'].split(".")[0])["index"]
    return "You clicked marker {} (number of times = {})".format(marker_id, value)


if __name__ == '__main__':
    app.run_server(debug=False)
```
You'll need to update Dash to 1.11.0 to enable wildcard callbacks and Dash Leaflet to 0.0.5 to enable the `n_clicks` property.

**Comment by acoque** [comment]
Yeah, thanks a bunch mate !
I didn't know the *pattern-matching callback* feature and it looks like (used with a dl.LayerGroup) it could do the job.

**Comment by SimonKnorke** [comment]
That's amazing! I was just having this issue with having dynamically generated markers in a LayerGroup. You just solved this problem! I really appreciate your dedication to the package.
Cheers.

**Comment by milanzmitrovic** [comment]
Nice work!!! Will this work for Polyline also?

**Comment by milanzmitrovic** [comment]
Actually, it works... Here is example...

import json
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input, ALL, State


# Create app.
app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dl.Map(
        children=[
            dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"),

            dl.Polyline(
                id='polyline',
                positions=[[57, 10], [57, 11], [56, 11]]
            ),

        ],
        style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8, id="map"
    ),
    html.H1(id='log_2')
], style={"position": "relative", 'width': '1000px', 'height': '500px'})


@app.callback(
    Output(component_id='log_2', component_property='children'),
    Input(component_id='polyline', component_property='n_clicks'),
    State(component_id='polyline', component_property='clickData')
)
def f1(input_, state_):
    print(json.dumps(input_))
    print(json.dumps(state_))
    print('----------------------')
    return input_


if __name__ == '__main__':
    app.run_server(debug=False)
