### ISSUE TITLE
How to install dash_leaflet.express?

### ISSUE THREAD

**Issue by Hootie9lives** [thedirtyfew/dash-leaflet#53]
Hi Emil,

I tried to import dash_leaflet.express. It complained about geobuf. I am curious if you can inform me on how to set up geobuf to use dash_leaflet.express?

**Comment by emilhe** [comment]
If you install it via pip, it should work?

**Comment by Hootie9lives** [comment]
It errors at import dash_leaflet.express as dlx. When I tried to install Geobuf, it said it was already installed

**Comment by Hootie9lives** [comment]
![image](https://user-images.githubusercontent.com/28104489/97302172-146ab880-182f-11eb-8247-e8ff5a23eade.png)

**Comment by emilhe** [comment]
It seems that you have a problem with your geobuf installation.

**Comment by wuestnjo** [comment]
I had the same error. Installing geobuf resolved the error. 
https://pypi.org/project/geobuf/

`pip install geobuf`

**Comment by matttob** [comment]
HI I'm having the same problems and get the following:

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

I'm just wondering if you managed to resolve this issue 

thanks a lot

Matt
