### ISSUE TITLE
Are custom markers supported? [question]

### ISSUE THREAD

**Issue by alejandrodemiquel** [thedirtyfew/dash-leaflet#54]
First of all, thanks for building this package. It's a great tool for building dashboards with interactive maps.

I've been trying to use custom makers with your package, and I can't manage to do it. I don't get any errors, but the markers are just not shown. Not sure if this is an issue with the package or with the code. This is an example:

```
import dash
import dash_leaflet as dl
import dash_bootstrap_components as dbc

app = dash.Dash(__name__, external_stylesheets =[dbc.themes.BOOTSTRAP])

marker = dl.Marker(
                position=[40, 0],
                id='marker',
                icon={'iconUrl': 'Blue.png', 'iconSize': [50, 50]}
            )

map = dl.Map([dl.TileLayer(),marker],
             id='map',
             center=(40, 0),
             zoom=6,
             style={'width': '800px', 'height': '300px'}
        )

app.layout = dbc.Container(map)

if __name__ == '__main__':
    app.run_server(host='0.0.0.0', debug=True, port=5000)
```

The icon I'm trying to add is of course 'Blue.png', and the path is correct. Note that if I want to use the default marker the program works fine, as expected.
Sorry for asking this question here; couldn't find any other way to do it.

**Comment by emilhe** [comment]
Thanks! I think the proper ways to ask questions would be StackOverflow, git issues are more suitable for e.g. bugs. That being said, custom markers _are_ supported. You code seems OK, so my guess would be that the provided url `Blue.png` is not valid. For reference, here is a small self contained example. 

```
import dash
import dash_html_components as html
import dash_leaflet as dl

# Setup icon options, example from Leaflet doc (https://leafletjs.com/examples/custom-icons/).
icon = {
    "iconUrl": 'https://leafletjs.com/examples/custom-icons/leaf-green.png',
    "shadowUrl": 'https://leafletjs.com/examples/custom-icons/leaf-shadow.png',
    "iconSize": [38, 95],  # size of the icon
    "shadowSize": [50, 64],  # size of the shadow
    "iconAnchor": [22, 94],  # point of the icon which will correspond to marker's location
    "shadowAnchor": [4, 62],  # the same for the shadow
    "popupAnchor": [-3, -76]  # point from which the popup should open relative to the iconAnchor
}
# Create example app.
app = dash.Dash()
app.layout = html.Div([
    dl.Map([dl.TileLayer(), dl.Marker(position=(56, 10), icon=icon)],
           id="map", style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}),
])

if __name__ == '__main__':
    app.run_server()
```

**Comment by alejandrodemiquel** [comment]
Yes, that works for me too. I'll have to look into what the issue with my png is.

Thanks a lot!
