### ISSUE TITLE
Changing the icon on a geojson layer

### ISSUE THREAD

**Issue by spamula** [thedirtyfew/dash-leaflet#55]
Is this possible? I've looked up the leaflet docus and it seems to be but I can't seem to get this working, can anyone point me in the right direction?

**Comment by emilhe** [comment]
Yes, it is possible. Just create a new PointToLayer function as described in the docs,

https://dash-leaflet.herokuapp.com/#func_props

which returns the desired icon.

**Comment by spamula** [comment]
Works perfectly, I know 0 js as well so I tried the dash_transcrypt approach first with no luck but managed! Thanks 👍
