### ISSUE TITLE
Dash leaflet with esri leaflet or esri WMS Tilelayers... is it possible to get this to work?

### ISSUE THREAD

**Issue by spamula** [thedirtyfew/dash-leaflet#57]
I've been trying to add a WMS Tilelayer from an arcgis service with not much luck, with a basic tutorial via esri leaflet I can get something like: https://eerscmap.usgs.gov/uswtdb/data/ to work but when I try via dash leaflet it seems to have difficulties rendering.

Can anyone point me in the right direction on how to proceed with implementing tilelayers from arcgis servers?

**Comment by emilhe** [comment]
Could you post an example of your current code which is not rendering as intended?

**Comment by emilhe** [comment]
After looking a little more at the library, I would say that you _can_ make it work, but it will take significant effort, as each of their custom components would need to be ported into a Dash (React) component.
