### ISSUE TITLE
Geolocation on Mobile

### ISSUE THREAD

**Issue by NightFury555** [thedirtyfew/dash-leaflet#6]
Hi!
Thank you for coming out with this package!
Would like to ask if it is possible to incorporate geolocation on mobile? Or acquire the user's current lat/long using this mean?

[https://leafletjs.com/examples/mobile/](url)

**Comment by emilhe** [comment]
Geolocation is currently not implemented. I am not sure when i get the time to implement it, but assuming that i did - how do you think it should work?

The first question is, what should trigger the ask-for-location dialogue. Should it just be on map initialization? Or should the map have a property, say `n_locate`, that triggers the dialogue, when its value is changed? Or something else? 

The next question is, how the location data should arrive in Dash. Should the map have a `location` property, which is updated after the dialogue is accepted? Or something else?

**Comment by NightFury555** [comment]
I have managed to make your folium work by returning via iFrame instead. This cannot seem to return the coordinates back to dash though.

If implemented, I hope it could return to dash values like 'ClickData' when used with scatterMapbox.  Additionally, it will be great if the LocateControl can somehow output the latlong

**Comment by emilhe** [comment]
I have just added support for geolocation (version 0.0.7). It can be enabled by adding a LocateControl to the map object. Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl

app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"), dl.LocateControl()],
           style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8, id="map", maxZoom=20),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server()

```
I haven't tested it much though, so please let me know if it works as intended.

**Comment by NightFury555** [comment]
> I have just added support for geolocation (version 0.0.7). It can be enabled by adding a LocateControl to the map object. Here is a small example,
> 
> ```
> import dash
> import dash_html_components as html
> import dash_leaflet as dl
> 
> app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
> app.layout = html.Div([
>     dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"), dl.LocateControl()],
>            style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8),
> ], style={"position": "relative", 'width': '1000px', 'height': '500px'})
> 
> if __name__ == '__main__':
>     app.run_server()
> ```
> 
> I haven't tested it much though, so please let me know if it works as intended.

Thank you so much for your update! Tested and it works.

- However, may I ask what is the difference with embedding Folium within an iFrame like I did earlier?

- How is it possible to implement a app.layout with a app.callback for a simple CircleMarker?

- And also, is it possible for your dash-leaflet integration to return the Lat/Long of the Geolocation and also the 'Click' Lat/Long back to dash?

**Comment by emilhe** [comment]
That sounds great!

* Folium is not integrated with the Dash eco system. Hence, it is (to my knowledge) not possible to propagate information from the Folium map back to Dash (e.g. clicks on the map, on markers, etc.). 

* I am not sure i understand the question? You can add CircleMarkers to the map as show here,

https://github.com/thedirtyfew/dash-leaflet/blob/master/usage_gallery.py#L47

* Yes, it is possible to use the click lat lon from the map. Here is an example,

https://github.com/thedirtyfew/dash-leaflet/blob/master/usage_gallery.py#L89

I haven't implemented the possibility to capture lat lon of the geolocation action, but i guess it would make sense to do so. I'll probably look into it within the next days.

**Comment by NightFury555** [comment]
> That sounds great!
> 
> * Folium is not integrated with the Dash eco system. Hence, it is (to my knowledge) not possible to propagate information from the Folium map back to Dash (e.g. clicks on the map, on markers, etc.).
> * I am not sure i understand the question? You can add CircleMarkers to the map as show here,
> 
> https://github.com/thedirtyfew/dash-leaflet/blob/master/usage_gallery.py#L47
> 
> * Yes, it is possible to use the click lat lon from the map. Here is an example,
> 
> https://github.com/thedirtyfew/dash-leaflet/blob/master/usage_gallery.py#L89
> 
> I haven't implemented the possibility to capture lat lon of the geolocation action, but i guess it would make sense to do so. I'll probably look into it within the next days.

- This is where your packages comes in? We would be able to click on the markers and send the LatLong back to Dash?

- Thanks again for your detailed write-up and examples. I have pour through the usage gallery, but I am unable to map more than a point from a dataframe. Would you be able to give an example of plotting a dataframe with the lat/long and attribute? I did something like this but it does not work.
`        dl.CircleMarker(
            center = [[1.306644045, 103.8492042], [1.306064115, 103.8490875]],
                radius=10,
                color=Top_X['marker_color'],
                fill = True,
                children =[
                dl.Tooltip('This is Tooltip!'),
                dl.Popup(
                    [
                        html.H1("Marker popup"),
                        html.P("with inline html")
                    ]
                )
                ]
        )`

- Thank you for adding in the geolocation feature! Having the Lat Lon being captured and used for something like re-centering the map or for doing some calculations, would be a really wonderful feature.

Hope to hear more good news, Thank you for your effort again!

**Comment by emilhe** [comment]
* Yes, with dash-leaflet, you can trigger callbacks in Dash, e.g. when markers or the map itself is clicked.

* You need to create one marker per (lat,lon) pair. Something like,

```
import dash
import dash_html_components as html
import dash_leaflet as dl

# Create markers.
LatLonList = [[1.306644045, 103.8492042], [1.306064115, 103.8490875]]
markers = [dl.CircleMarker(center=latlon) for latlon in LatLonList]
# Create app.
app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png")] + markers,
           style={'width': "100%", 'height': "100%"}, center=[1.306644045, 103.8492042], zoom=17, id="map", maxZoom=18),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server()
```

* I have just added a `location_lat_lon_acc` property to the map so that the user location can be accessed from Dash (version 0.0.8). Here is an example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl
from dash.dependencies import Output, Input

app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"), dl.LocateControl()],
           style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8, id="map", maxZoom=20),
    html.Div(id="text"),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})

@app.callback(Output("text", "children"), [Input("map", "location_lat_lon_acc")])
def update_location(location):
    if location:
        return "You are within {} meters of (lat,lon) = ({},{})".format(location[2], location[0], location[1])

if __name__ == '__main__':
    app.run_server()
```

**Comment by NightFury555** [comment]
> * Yes, with dash-leaflet, you can trigger callbacks in Dash, e.g. when markers or the map itself is clicked.
> * You need to create one marker per (lat,lon) pair. Something like,
> 
> ```
> import dash
> import dash_html_components as html
> import dash_leaflet as dl
> 
> # Create markers.
> LatLonList = [[1.306644045, 103.8492042], [1.306064115, 103.8490875]]
> markers = [dl.CircleMarker(center=latlon) for latlon in LatLonList]
> # Create app.
> app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
> app.layout = html.Div([
>     dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png")] + markers,
>            style={'width': "100%", 'height': "100%"}, center=[1.306644045, 103.8492042], zoom=17, id="map", maxZoom=18),
> ], style={"position": "relative", 'width': '1000px', 'height': '500px'})
> 
> if __name__ == '__main__':
>     app.run_server()
> ```
> 
> * I have just added a `location_lat_lon_acc` property to the map so that the user location can be accessed from Dash (version 0.0.8). Here is an example,
> 
> ```
> import dash
> import dash_html_components as html
> import dash_leaflet as dl
> from dash.dependencies import Output, Input
> 
> app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
> app.layout = html.Div([
>     dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"), dl.LocateControl()],
>            style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8, id="map", maxZoom=20),
>     html.Div(id="text"),
> ], style={"position": "relative", 'width': '1000px', 'height': '500px'})
> 
> @app.callback(Output("text", "children"), [Input("map", "location_lat_lon_acc")])
> def update_location(location):
>     if location:
>         return "You are within {} meters of (lat,lon) = ({},{})".format(location[2], location[0], location[1])
> 
> if __name__ == '__main__':
>     app.run_server()
> ```

Thank you so much for your examples! I managed to deploy it into what I wanted to do. It works perfectly!

- On the markers being clicked and triggering a callback, is there a particular property? In the regular Dash Scattermapbox, it would be the equivalent of `ClickData`.

- One feedback is that using the current stylesheet, the dropdown menu would be blocked by the map itself. Is there a possible fix to this? 

Thank you for your work and effort again!

**Comment by emilhe** [comment]
* For markers, the property is n_clicks. Like for dash buttons, it is a counter that is increased on click.

* I haven’t done any of the styling myself, so I can’t comment on this part. Probably it has to do with the z-index of the map versus the drop down. It should be relatively easy to override manually.

Great to hear that it works 👍

**Comment by NightFury555** [comment]
- I noticed that the property to return the Lat Long is `click_lat_lng` . It worked brilliant 👍 

- Thanks for the tips there! I found out that dash uses `zIndex` instead of the HTML `z-index`. The problem is solved.

A new observation I have is that everytime I changed tabs in my dashboard, the Geolocation icon goes away and I can no longer activate it until I refresh my browser. I have a Datatable in the other tab. Not sure if you are aware of this. Thanks!

**Comment by SimonKnorke** [comment]
Hey! 

There seems to be a problem with the accuracy of the location point, especially when you are outdoors and not standing still. The accuracy radius might get quite large (>500m) and the location dot is jumping around.
Is there a way to trigger the location information more frequently or to set a wanted level of accuracy?

There would be a corresponding solution for leaflet.js:
https://github.com/M165437/Leaflet.AccuratePosition/blob/master/Leaflet.AccuratePosition.js

The received position is checked and, if necessary, updated if it is not accurate enough.
How could a feature like this be incorporated into the dash-leaflet framework?

**Comment by SimonKnorke** [comment]
Update: For now I fixed this issue by changing some locateOptions in the LocateControl component:

`dl.LocateControl(options={'locateOptions': {'enableHighAccuracy': True, 'watch': True}})`

**Comment by emilhe** [comment]
That was exactly the solution i would have suggested, but I didn’t want to post before I had the chance to test it. Is the accuracy as expected?

**Comment by SimonKnorke** [comment]
I checked the parameter setting and I' m quite happy with it.
The correct position (with a natural uncertainty of ~5m) is now displayed quite fast and the map responds to changes with accuracy comparable to the known map services!.

I would recommend this option despite the higher power consumption, unless the user moves very little or the location information can be increased e.g. by a Wifi connection.

**Comment by emilhe** [comment]
Thank you for the feedback. I just tried it out, and it seems to work well for me also. I will include this setting in the geolocation example in the documentation that i am working on :)

**Comment by emilhe** [comment]
The example is now available [here](https://dash-leaflet.herokuapp.com/#locate_control).

**Comment by emilhe** [comment]
I just tried to reproduse the Tab issue reported by @NightFury555 , but it works fine for me using Dash 1.12.0. If the issue persists, please report it as a seperate issue along with system info (OS, Dash version, etc. ...) and a mwe demonstrating the problem.
