### ISSUE TITLE
Exporting map as a figure

### ISSUE THREAD

**Issue by SarvaPulla** [thedirtyfew/dash-leaflet#60]
Thank you for putting the package together. Has opened up a lot of possibilities through dash. Is there anything in the current setup where one can export the Map div/object as a figure? Would be happy to discuss or try any workflows that you think might be worth exploring. Thanks.

**Comment by emilhe** [comment]
I guess this could be an option,

https://github.com/rowanwins/leaflet-easyPrint

Or do you need server side rendering?

**Comment by SarvaPulla** [comment]
That's a good start. Will look into it. Server side rendering would be a nice bonus.

**Comment by emilhe** [comment]
I was asking about server side rendering, as client side rendering vs. server side rendering will probably require two different setups. At a glance, client side rendering seem to be the easiest to implement in dash-leaflet context :)

**Comment by SarvaPulla** [comment]
Sorry forgot about this thread. How would server side setup look like?
