### ISSUE TITLE
Map view not changing with bounds change (v0.1.11)

### ISSUE THREAD

**Issue by Folgrim** [thedirtyfew/dash-leaflet#62]
Firstly, I appreciate the fix for maps in tabs, however I suspect that the fix is the cause of this issue.

Changing the bounds of the map via callback no longer changes the actual view on the map itself.  I have confirmed that the bounds prop change does indeed occur, but it doesn't update the map view itself.  This wasn't an issue prior to 0.1.11.

**Comment by emilhe** [comment]
Yes, that is a side effect of the fix. To change the map view, you would now need to update the viewport.

**Comment by Folgrim** [comment]
Unfortunately changing the viewport is much more difficult when displaying dynamic data in a dynamically sized map, given how much the extent of the data and the pixel size of the map will effect the ideal zoom level.  If we at least somehow had access to the getBoundsZoom leaflet method, or the math behind it, we could potentially do that calculation and set the viewport accordingly.  Effectively, what fitBounds does, but without actually using the bounds prop, if that prop is now off-limits due to the tab issue.

**Comment by emilhe** [comment]
Ah, i see. Maybe i should take another stab at getting both features to work simultaneously (:

**Comment by emilhe** [comment]
I think i managed to get it working with all of the special cases. I have made a pre-release on pypi with the changes, 

https://pypi.org/project/dash-leaflet/0.1.12rc1/

Could you test it for your usecase?

**Comment by Folgrim** [comment]
Thanks!  I won't be able to test it in my larger project until next week but I wrote up a quick MWE, and I included multiple maps on separate tabs (which isn't my current use case but wanted to check that for others).  The bounds are updating the view as expected, and keeping to their respective maps.  Looks great!  Well done.

**Comment by emilhe** [comment]
Thanks! I haven't founds any bugs either, so decided to push a new non-rc release with the fix,

 https://pypi.org/project/dash-leaflet/0.1.12/
