### ISSUE TITLE
Starting with 'display':'none' property

### ISSUE THREAD

**Issue by remiOdite** [thedirtyfew/dash-leaflet#64]
Hi all,

I started to use this extension for my dash app. For some reason I need to hide the map on the beginning, and showing it after a specific callback.

But if I create the Div with the style property 'display':'none', which encapsulate the dl.Map object, and then switch back to 'display':'block', the map display bug. There is a screenshot :

![bug_leaflet](https://user-images.githubusercontent.com/49723350/102317827-8aaab200-3f78-11eb-866a-accf7da587a5.png)

If I show the map at the beginning, then hide it, then re-show it, there is no bug. But I really need to hide the map at the dash app creation.

If anyone encounter this issue and have an idea to solve it

thank's in advance ! 
Regards

**Comment by emilhe** [comment]
Are you using the latest version?

**Comment by remiOdite** [comment]
I was using the version 0.1.11. I just upgraded to the latest one, and the bug still occurs.

I just noticed that the map is displayed correctly if I resize the window. This is not really a solution, but maybe it can help you to identify the bug ;)

FYI, I defined the height and width in px of all parent divs, and for the dl.Map object also.

**Comment by emilhe** [comment]
I think i have seen this before. My guess would be that it's a matter of React not triggering a render when you change the style of the parent div. Depending on you app, one possible solution might be to add/remove the `Map` element instead of hiding it.

**Comment by remiOdite** [comment]
- Add/remove the dl.Map object works
- Add/remove the dl.TileLayer instead (children of dl.Map) does not works (I tested it by curiosity)

So, it seems that your guess is the good one. Do you think it is possible to easily force React to re-render the component after changing the style of the parent div ? If not, I will keep your first solution.

Thank you very much !

**Comment by emilhe** [comment]
I don't think there is any easy way to do it from Dash. It might be sufficient to change the ID of `Map` component (i haven't tested), but even if it works, i find the approach of simply adding/removing the component much less hacky.

**Comment by remiOdite** [comment]
Ok thank you very much for your support. I will then keep your solution of adding/removing the component.

**Comment by michelkok** [comment]
I have the same issue. The tiles are only loaded when I resize the browser window. For me, it is also upon initial render, and entirely rerendering a new `dlc.Map` does not solve it.

By the way, a quick google search showed that it happens also outside of dash environments. 

<img width="685" alt="image" src="https://github.com/emilhe/dash-leaflet/assets/25588435/487e99c3-112b-447a-8c9f-33b58d96a721">

Part of the code for reference:
```
# Layout.py
def _map_view() -> dmc.Stack:
    return dmc.Stack(
        children=[
            dmc.Col(
                id=f"{ID_PREFIX}_map_col",
                style={"display": "none"},
                children=[
                    dmc.Stack(
                        id=f"{ID_PREFIX}_map_stack",
                    )
                ],
            ),
            # Empty component used to trigger only when we want.
            dmc.LoadingOverlay(
                children=dmc.Col(
                    id=f"{ID_PREFIX}_loader_map", style={"display": "none"}
                ),
            ),
        ],
        justify="center",
    )
```
```
# From callbacks.py
maps_style = {"display": "none"}
center_point = None
if len(gps) > 0:
    maps_style = {"height": "60vh"}
    lat, lng = list(zip(*gps))
    center_point = [lat[0], lng[0]]
    if len(lat) > 1:
        # Assume the earth is locally flat and as such approximate the center.
        center_point = [sum(lat) / len(lat), sum(lng) / len(lng)]

markers = [
    dl.CircleMarker(center=[x[0], x[1]], radius=10, color="red") for x in gps
]
mp_children = [dl.TileLayer()] + markers  # noqa

new_map: list[Component] = [dl.Map(
    id=f"{ID_PREFIX}_map",
    children=[dl.TileLayer()],
    center=center_point,
    zoom=6,
    style=maps_style,
)]
```
I'm updating the `children` prop of `f"{ID_PREFIX}_map_stack"`.

Any thoughts?

**Comment by emilhe** [comment]
If the issue is present in native Leaflet, it is expected to be present in dash-leaflet.

That being said - if we can find a fix, it could be ported to be part of dash-leaflet :)

**Comment by michelkok** [comment]
The fix usually incorporates a call to `map.invalidateSize()`. Would there be a way to call this from this repo?
