### ISSUE TITLE
GeoJSON component does not show up on map

### ISSUE THREAD

**Issue by boeleman** [thedirtyfew/dash-leaflet#65]
Hello,

Thank you so much for writing dash-leaflet. I am looking forward to using it.

I am trying make a choropleth map and I started with our example on heroku. However, only the map and color bar gets shown, but not the contents of the json file. I do not get any error messages. Any suggestions on how to debug this?

Thanks,

Arnout

**Comment by emilhe** [comment]
Did you put us-states.json in the assets folder?

**Comment by boeleman** [comment]
Yes, and dash gives a code 200 that it found the file.

**Comment by emilhe** [comment]
What package versions do you have? The example is running with

pip install dash==1.18.1
pip install dash-leaflet==0.1.12
pip install dash-extensions==0.0.41

**Comment by boeleman** [comment]
$ pip3 list |grep dash
dash                   1.18.1
dash-core-components   1.14.1
dash-extensions        0.0.41
dash-html-components   1.1.1
dash-leaflet           0.1.12
dash-renderer          1.8.3
dash-table             4.11.1

Running on Debian testing

**Comment by boeleman** [comment]
Hi Emil,

I figured it out. I was under the assumption that I could put the geojson
files in another directory than assets, but that does not seem to be the
case. Also, my Coordinate Reference Systems was wrong. After changing it
to 'EPSG:4326' everything is working now.

Cheers,

Arnout
