### ISSUE TITLE
Zoom in/out using ctrl

### ISSUE THREAD

**Issue by remiOdite** [thedirtyfew/dash-leaflet#66]
Hi !

I'd like to enable zoom in/out with mouse wheel **only when clicking on ctrl key**. This in order to prevent zoom in/out when I'm scrolling the web page.

Is there a way to do it ?

Thank's in advance !
Best regards

**Comment by emilhe** [comment]
I haven't implemented anything in the Dash layer, but there seems to be a few JS solutions available,

https://stackoverflow.com/questions/45982643/leaflet-js-use-ctrl-scroll-to-zoom-the-map-move-map-with-two-fingers-on-mob

**Comment by remiOdite** [comment]
I found this solution yesterday also, but I did not succeed to implemented it. I read that Jquery DOM events were not compatible with react components. 

But I did not insist. I will try harder in the next few days and let you know If I found a working solution.

**Comment by remiOdite** [comment]
I re-try to enable zoom in/out using ctrl, but the provided solution need to access elements using the DOM. Unfortunately, it seems impossible to access DOM element on a react application.

So, it seems to be a dead end. If anyone have any other idea ? Maybe this improvement should be implemented first in react-leaflet ?

**Comment by emilhe** [comment]
At a glance, I think the best approach would be to add a new component that wraps,

https://github.com/elmarquis/Leaflet.GestureHandling

It seems to do what you need - and more (:

**Comment by emilhe** [comment]
I just made a quick wrapper. It's used like this,

```
import dash
import dash_leaflet as dl

app = dash.Dash()
app.layout = dl.Map([dl.TileLayer(), dl.GestureHandling()], style={'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server()
```

You can try it in out in `dash-leaflet==0.1.16rc3` :)

**Comment by remiOdite** [comment]
That's work perfectly ! Thank you very much ! :+1:

**Comment by emilhe** [comment]
The feature has been incorporated in the `dash-leaflet==0.1.16` release.

**Comment by emilhe** [comment]
@remiOdite Thanks for posting the issue! I have just added `GestureHandling` components to a few of my apps, and only now I realize how much the default scrolling behavior annoyed me (:
