### ISSUE TITLE
Plugin for Fullscreen Control

### ISSUE THREAD

**Issue by SimonKnorke** [thedirtyfew/dash-leaflet#67]
Hello, 

First of all, thumbs up for this great and amazingly fast developing package!  

I would find a full screen control on the map very handy as it would greatly increase the mobile usability of any webapp containing a dash-leaflet map. You wouldn't waste precious space on app borders that way. 

I'm referring to leaflet plugins https://github.com/brunob/leaflet.fullscreen and react-leaflet wrapper https://github.com/krvital/react-leaflet-fullscreen.

Unfortunately I do not know how much effort is the integration, but it would be quite amazing:)

**Comment by emilhe** [comment]
Thanks! I have actually been thinking about a full screen control many times, but i just never got around to it. Thanks for the links, with the react component at hand, it didn't require much effort to draft an implementation. It is available in `dash-leaflet==0.1.13`. The current syntax looks like this,

```
_import dash
import dash_leaflet as dl

app = dash.Dash(external_stylesheets=['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'])
app.layout = dl.Map([dl.TileLayer(), dl.FullscreenControl()], style={'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server()_
```

**Comment by SimonKnorke** [comment]
Wow. The new feature works perfectly, I have just tested it on my devices. . Thank you very much for your effort!

**Comment by ikhomyakov** [comment]
Cool stuff! Thanks @emilhe!

Worked perfectly in Chrome and Firefox, however, it didn't work in Safari Version 14.0.2 (15610.3.7.1.10, 15610) on Mac OS Catalina 10.15.7. (Also please note that in Safari marker's popups do not open on click.) 

Re fontawesome: it is awesome but if someone doesn't want to depend on it, is there an option to use full screen feature without using fontawesome?

**Comment by emilhe** [comment]
Thanks! The icons are currently hardcoded (though that could easily be changed). But I guess you could change the icon be defining classes with the same names as in font awesome.

If you want a ‘real’ custom leaflet control, you would have to implement it in the React layer. In Dash, you can get some of the way [using a div on top of the map](https://dash-leaflet.herokuapp.com/#choropleth_us).

**Comment by ikhomyakov** [comment]
> The icons are currently hardcoded (though that could easily be changed). But I guess you could change the icon by defining classes with the same names as in font awesome.
Sounds good. 

> If you want a ‘real’ custom leaflet control, you would have to implement it in the React layer. In Dash, you can get some of the way using a div on top of the map.
I have been using this approach, however, it doesnt work well with Full Screen control -- the divs disappear in full screen mode.

Did you have a chance to test dash-leaflet in Safari? Let me know if you require more specific information on how to reproduce the "click" issues in Safari.

**Comment by emilhe** [comment]
Sorry, I only use Chrome, so I can’t comment on the behavior in Safari.

**Comment by befedo** [comment]
> Thanks! The icons are currently hardcoded (though that could easily be changed). But I guess you could change the icon by defining classes with the same names as in font awesome.
> 
> If you want a ‘real’ custom leaflet control, you would have to implement it in the React layer. In Dash, you can get some of the way [using a div on top of the map](https://dash-leaflet.herokuapp.com/#choropleth_us).

Hi there,

I've tried the solution and got a follow up question (not related to the fullscreen control). I've placed a `dash_core_components.Input`on top of my map. Each time the `Input` get's clicked the underlying map gets also a `click_lat_lng`event.

Is there any way to prevent this?

best regards and thanks for your time

**Comment by shaun-adam** [comment]
Glad I stumbled on to this today.

Just dropping a note here that this isn't listed in the controls that have been brought over from leaflet in the docs yet.
