### ISSUE TITLE
Error when setting TileLayers() bounds property

### ISSUE THREAD

**Issue by ljburtz** [thedirtyfew/dash-leaflet#68]
Hello and thank you for making this very useful software!

I'm working with TileLayer to display tiles from a Tile Management Service. 
The tiles are not available for the entire world, just a small region. So I want to set the bounds property of my TileLayer component

It works great when app.run_server(debug=False) but fails when debug=True.

The failure is characterized by the browser not loading anything or, after about 1 min this error appears:
![image](https://user-images.githubusercontent.com/26211495/104538454-3d952b00-565f-11eb-8fdd-b0acba695866.png)

Do you have insight on why this differnce between debug mode True or False?

I use the usual list of list for the bounds coordinates: `bounds =  [[41.906621, -87.649784], [41.840409, -87.592793]]`
(I tried a flattened list to have bound[0,] be an int but it does not work at all)
Here is the error in full.

> (This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
> Error: Invalid argument `bounds[0]` passed into TileLayer.
> Expected `number`.
> Was supplied type `array`.
> 
>     at propTypeErrorHandler (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/dash_renderer.v1_8_3m1604054361.dev.js:98421:9)
>     at CheckedComponent (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/dash_renderer.v1_8_3m1604054361.dev.js:92763:77)
>     at renderWithHooks (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:14938:20)
>     at mountIndeterminateComponent (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:17617:15)
>     at beginWork (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:18731:18)
>     at HTMLUnknownElement.callCallback (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:182:16)
>     at Object.invokeGuardedCallbackDev (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:231:18)
>     at invokeGuardedCallback (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:286:33)
>     at beginWork$1 (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:23338:9)
>     at performUnitOfWork (http://127.0.0.1:8052/_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1604054361.14.0.js:22292:14)

Here is a toy example to reproduce
```
import dash
import dash_leaflet as dl
import dash_html_components as html

spot_url = 'assets/tiles/spot/{z}/{x}/{y}.png'
# geotif of chicago downloaded from https://download.osgeo.org/geotiff/samples/spot/chicago/SP27GTIF.TIF
# geotif made into tiles with gdal command line: gdal2tiles.py --zoom=1-20 SP27GTIF.tiff tiles/spot/
spot_bounds = [[41.906621, -87.649784], [41.840409, -87.592793]]

error_url = 'assets/tiles/error_tile.png'

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        dl.Map(
            [
                dl.TileLayer(),
                dl.TileLayer(
                    url=spot_url,
                    maxZoom=20,
                    tms=True,
                    errorTileUrl=error_url,
                    opacity=0.5,
                    bounds=spot_bounds,
                ),
            ],
            center=(41.874546, -87.625408), zoom=13
        )
    ],
    style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block", "position": "relative"}
)


if __name__ == '__main__':
    app.run_server(debug=False)   # debug=True does not work!!
```
If I don't set the bounds property, then I get 404 errors url not found and the errorTileUrl get's loaded
![image](https://user-images.githubusercontent.com/26211495/104541044-23118080-5664-11eb-80ff-404efc088087.png)

I wonder if this error comes from dash-leaflet or deeper into dash itself. Any help and pointers much appreciated! Thanks!

**Comment by emilhe** [comment]
Since if works without debug=True, it is a simple bug in the property validation in Dash leaflet. The bounds property is validated like this,

    bounds: PropTypes.arrayOf(PropTypes.number),

but i guess it should have been,

    bounds: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.number)),

I have made a pre release with the fix that you can try out,

https://pypi.org/project/dash-leaflet/0.1.14rc1/

Please let me know if it works as intended. If it does, I'll include it in the next release.

**Comment by remiOdite** [comment]
Hi ! 

I'm facing this issue, could it be possible to include this fix in the next release ? It looks like you fixed the bug, I tested your pre release
