### ISSUE TITLE
Make contour and contourf plot in dash_leaflet

### ISSUE THREAD

**Issue by yvonneg** [thedirtyfew/dash-leaflet#69]
Hi, I have used the geojsoncontour module (https://pypi.org/project/geojsoncontour/) to convert matplotlib contour plots to geojson. Do you know if its possible to read this file in dash-leaflet and how?

**Comment by emilhe** [comment]
It should be possible, how to do it depends on what you are trying to achieve. I guess if you want the lines, you could use the `GeoJSON` component. If you want filled contours, you could create tiles with a tool of your choice and serve them to the leaflet map using the `TileLayer `compoent.

**Comment by yvonneg** [comment]
Thank you for your quick reply. 

It works, but for some reason i need to save the output from geojsoncontour and open the file again in python with json to make it work in dash_leaflet. So, finally I get the lines on a map. But every line has the same color (blue). I also get the filled contours, but with the same blue color. How can I let dash_leaflet know the colors of each line given in the geojson file? I guess I need to give some information in the options part of dl.GeoJSON, and if not is there a tutorial on how to create the tiles for the TileLayer? I want to keep the OSM. I guess the biggest problem is my lack of knowledge when it comes to leaflet and using geojson files. This is my code now:

with open("contourf.geojson") as f:
    data_contourf = json.load(f)

app = dash.Dash()
app.layout = html.Div([
    dl.Map([dl.TileLayer(),dl.GeoJSON(data=data_contourf)],
#    dl.Map([dl.TileLayer(CREATE TILES?),dl.GeoJSON(data=data_contourf, options=?)],       #??? How to?
           style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"})
])

if __name__ == '__main__':
    app.run_server()    

The GEOJSON file is long, but showing here the first "geometry" of the geojson file which I use for testing:

{"features":[{"geometry":{"coordinates":[[[[3.356,80.549],[3.477,80.539],[3.581,80.555],[3.704,80.561],[3.735,80.567],[3.799,80.587],[3.855,80.607],[3.734,80.618],[3.734,80.618],[3.62,80.679],[3.432,80.669],[3.246,80.66],[3.174,80.641],[3.118,80.62],[3.118,80.62],[3.177,80.59],[3.298,80.579],[3.356,80.549]]]],"type":"MultiPolygon"},"properties":{"fill":"#ff5e00","fill-opacity":0.5,"stroke":"#0000ff","stroke-opacity":1,"stroke-width":2,"title":"-1.00--0.90 "},"type":"Feature"}],"type":"FeatureCollection"}

**Comment by emilhe** [comment]
If you use the `GeoJSON` component, you could also save the data to the assets folder and serve it directly from here via an url. This approach will typically be more performant. 

To get the right colors, you can use [functional properties](https://dash-leaflet.herokuapp.com/#func_props) to parse the style information. 

If you choose to go for tiles instead, you can add another tile layer on top of the OSM layer simply by creating another `TileLayer` component (with an URL to you tile server).

**Comment by yvonneg** [comment]
Thank you for your help.

Using the functional properties to style the filled contour, worked perfectly. My problem now is that I have a second GeoJSON file with contour lines from another data-set (not filled), that I need to plot on top of the filled contour as black lines. The geometry in the first GeoJSON file is of type: MultiPolygon, while the geometry in the second file is of type:LineString. The problem is that the filled contour lines (MultiPolygon) are always on top, covering the contour lines from the other file (LineString). Do you know how to fix this? I could not find out how to use the zIndex or bringToFront for this problem

**Comment by emilhe** [comment]
If you wrap each `GeoJSON` component in a `Pane` component and set the zIndex of their style, you can control which is on top.
