### ISSUE TITLE
New feature: marker cluster

### ISSUE THREAD

**Issue by rmmariano** [thedirtyfew/dash-leaflet#7]
I would like to suggest you a new feature to your application.

One thing I need to build using dash is a map where the markers are clustered, as described [here](https://leafletjs.com/2012/08/20/guest-post-markerclusterer-0-1-released.html) and [here](https://github.com/Leaflet/Leaflet.markercluster).

If you could add this feature to your component would be amazing.

Thank you so much.

**Comment by emilhe** [comment]
That is a pretty cool feature indeed! However, the interface (in terms of properties that can be changed) is rather extensive. Hence, for now, i have just ported the component itself (version 0.0.6). Here is a small example,

```
import dash
import dash_html_components as html
import dash_leaflet as dl

# Create marker cluster.
marker_data = {"a": (56, 10), "b": (56, 11), "c": (55, 10), "d": (55, 11)}
markers = [dl.Marker(title=key, position=marker_data[key]) for key in marker_data]
cluster = dl.MarkerClusterGroup(id="markers", children=markers)
# Create app.
app = dash.Dash(external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dl.Map(children=[dl.TileLayer(url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"), cluster],
           style={'width': "100%", 'height': "100%"}, center=[55.5, 10.5], zoom=8, id="map", maxZoom=20),
], style={"position": "relative", 'width': '1000px', 'height': '500px'})

if __name__ == '__main__':
    app.run_server()
```

It might still need some testing, and i guess that at least some of the properties should be made accessible from Dash. Did you have any particular ones in mind?

**Comment by garikhgh** [comment]
Hi, this is a awesome feature.
But how we could get the id's of the selected markers?

**Comment by emilhe** [comment]
An interactive example is now available [here](https://dash-leaflet.herokuapp.com/#marker_cluster).

**Comment by NightFury555** [comment]
Hi,

Thank you for the really nice documentation that you have added! I have learned quite a fair bit from there.
On the MarkCluster, how do I specify the available options such as "disableClusteringAtZoom". See  [Example outcome](https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld-maxzoom.388.html)

**Comment by rmmariano** [comment]
> An interactive example is now available [here](https://dash-leaflet.herokuapp.com/#marker_cluster).

Thank you so much for this feature. I will use it. :-)
I'm sorry to answer you late.

**Comment by emilhe** [comment]
@rmmariano - Better late than never ;). I have just (0.0.13) added an `options` property, which makes it possible to pass parameter to the markerclustergroup constructur. It should work for any non-functional properties, i.e. it should enable your use case, @NightFury555. I have updated the [example](https://dash-leaflet.herokuapp.com/#marker_cluster) accordingly; the options property is now used to color the polygon outlines red. For now, this leaves two main limitations,

* You cannot pass functional properties, e.g. you cannot change the marker cluster icon.
* No events have been linked to Dash, e.g. you cannot invoke a callback on marker cluster click.

**Comment by rmmariano** [comment]
No problem @emilhe, the important is to plot the clusters in this moment. :-)
If you have time to fix these limitations in the future, they would be great improvements, indeed.
Thank you again.
