### ISSUE TITLE
SuperCluster points disappear on zoom

### ISSUE THREAD

**Issue by imccreadie** [thedirtyfew/dash-leaflet#71]
Thanks for adding CRS support awhile back! I now noticed a weird issue with a particular set of clustered datapoints. I attached just the coordinate geojson data for that set and can replicate the issue without a tilelayer using the toy example below.

If you zoom in you can see points in the cluster start to appear (no where near the cluster marker they were apart of) and then disappear as you zoom in further.

Not sure if I am doing something incorrect with the data format, but I am using CRS Simple so I imagine that is playing a role. 

```
import dash_html_components as html                                                                                                                                                                                 
import dash_leaflet as dl
import dash_leaflet.express as dlx 
from dash import Dash
import pandas as pd
import json

with open("test.csv") as fh: 
    data = json.loads(fh.read())
app = Dash()
app.layout = html.Div([
    dl.Map([
        dl.GeoJSON(data=dlx.geojson_to_geobuf(data), format="geobuf", cluster=True),
    ], center=(0, 0), crs="Simple", zoom=1, style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}),
])

if __name__ == '__main__':
    app.run_server()
```

[example.zip](https://github.com/thedirtyfew/dash-leaflet/files/5870394/example.zip)

**Comment by emilhe** [comment]
Do you see the same issue when using the default CRS? The clusters are built using [supercluster](https://github.com/mapbox/supercluster), and I am not sure if this library supports non-default CRS.
