### ISSUE TITLE
Javascript error trying to run dash leaflet inside Jupyter

### ISSUE THREAD

**Issue by summerswallow-whi** [thedirtyfew/dash-leaflet#72]
I'm trying to run dash-leaflet using Jupyterdash.

Here's the python:
```
from jupyter_dash import JupyterDash
JupyterDash.infer_jupyter_proxy_config()
import dash_html_components as html
import dash_leaflet as dl

# Cool, dark tiles by Stadia Maps.
url = 'https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png'
attribution = '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a> '
# Create app.
app = JupyterDash(__name__)
app.layout = html.Div([
    dl.Map(dl.TileLayer(url=url, maxZoom=20, attribution=attribution))
], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block", "position": "relative"})
```

I end up getting Error loading dependencies. In my console I see a javascript error

```
Uncaught TypeError: Object(...) is not a function
    at Object.<anonymous> (VM5680 dash_leaflet.min.js:6)
    at n (VM5680 dash_leaflet.min.js:1)
    at Object.<anonymous> (VM5680 dash_leaflet.min.js:65)
    at n (VM5680 dash_leaflet.min.js:1)
    at Module.<anonymous> (VM5680 dash_leaflet.min.js:86)
    at n (VM5680 dash_leaflet.min.js:1)
    at VM5680 dash_leaflet.min.js:1
    at VM5680 dash_leaflet.min.js:1
```

Since I don't know how the whole python/javascript interaction works and this is in a minified file, I can't begin to diagnose why this is the case. Any clue what is causing this?

**Comment by emilhe** [comment]
It looks like an issue with Jupyters internal loading of the JavaScript files. I haven't used `JupyterDash` myself, so I am will not be of much help unfortunately. I guess the code works in "pure" Python?

**Comment by summerswallow-whi** [comment]
Thanks for the fast response. I've found this package to be very configurable. That is why I'm anxious to get this into Jupyter as it allows non developers to use it.

I suspect you might be right about jupyter or my container system since if I run Dash not JupyterDash I also get the same error. Where you might be able to help me is to explain where dash-leaflet.min.js comes from. Since I can't find the file anywhere I'm guessing it is somehow generated. If that's the case, would it be possible to generated a non-minified version so that it would be easier to pinpoint the issue. I've not worked with packages that use both javascript and python so I'm unfamiliar with the mechanism here.

**Comment by emilhe** [comment]
Ah, I read you initial post wrong, sorry. It looks like an issue with the JavaScript code itself, not the loading. What version are you running? On what system? I just tested your example with a clean environment (with the latest versions of dash and dash-leaflet), and it runs without errors.

**Comment by summerswallow-whi** [comment]
You are right. I was running an ancient version of dash. dash==0.39.0. I believe what happens is the Jupyter-dash in conda pulls this version. If I first install dash with conda, the most recent version is pulled.

Anyhow that seemed to fix it.
