### ISSUE TITLE
Hide overlapping points in supercluster, markers with colored tex

### ISSUE THREAD

**Issue by guidocioni** [thedirtyfew/dash-leaflet#79]
I love dash-leaflet because it avoids me having to use JS too much :) 
Unfortunately my apps are becoming more and more complex and I'm starting to believe that the only way of taking full advantage of all the plugins/customization available for leaflet is to start building the app directly into JS without having to port every feature in Python :( 
But I'm not done yet! 

I'm trying to build something really simple, that is a scatter plot of temperature measurements overlaid on a satellite/radar background updated in real time. I managed to do something acceptable (see attached figure) but I'm struggling to bring this even one step further. 

<img width="993" alt="Screen Shot 2021-02-28 at 12 14 40" src="https://user-images.githubusercontent.com/12760310/109416564-4f3c5300-79bf-11eb-9142-b6c965fc3680.png">
More precisely these are the things that I would like to change but could not find how to do it:

- instead than creating a `superCluster` of points within a certain radius using a symbol that shows how many points are clustered and that expands on the click action, I would like to just hide overlapping points and show just 1 point per superCluster defined with a certain radius. This will depend, of course, on the zoom level.  I could not find any way to do this in leaflet but I guess this is officially supported..no? 
- instead than using markers colored according to colorProp I would like to show only text showing the value of colorProp with a textfont color given also by colorProp. So basically a map of temperature values shown by text colored according to the value itself. It sounds more complicated than it actually is :D
<img width="583" alt="Screen Shot 2021-02-28 at 12 29 13" src="https://user-images.githubusercontent.com/12760310/109416795-9d058b00-79c0-11eb-80be-c9d24d4415e9.png">
 Is there a way to do this? Do I need to use the tooltip and to "lock" it in place as I found on some stackoverflow answers? Still it is not clear how I would implement something like this on the dash side.

Thanks for the really nice work!

**Comment by emilhe** [comment]
While you can only get the full flexibility by moving to JavaScript, I think what you are currently trying to do should be possible with dash-leaflet. 

* To disable zoom interaction, set `zoomToBoundsOnClick=False`
* To "hide" points instead of rendering clusters, I guess you could simply set the rendering of points and clusters to be the same (from a UI perspective, not the same function). If you do so, can't see what is a point/what is a cluster, but the clusters will still expand on zoom, which is guess is what you want
* To render numbers instead of dots, set the `pointToLayer` property for an appropriate function. And set the `clusterToLayer` prop to a similar function, where the numbers is based of e.g. the mean, or whatever makes the most sense in you application

**Comment by guidocioni** [comment]
Sorry for the late reply, I only had time today to try it out...

Unfortunately the use of the `pointToLayer` and `clusterToLayer` functions for me is still a little bit confusing, maybe because I'm not an expert of JS and Leaflet. The only way that I found to show text together with the points was to bind the tooltip like this

```javascript
window.myNamespace = Object.assign({}, window.myNamespace, {  
    mySubNamespace: {  
        pointToLayer: function(feature,latlng){
            label = String(feature.properties.name) 
            return new L.CircleMarker(latlng, {
              radius: 0.1,
            }).bindTooltip(label, {permanent: true, 
                direction: "center",
                className: "my-labels"}).openTooltip();
            } 
    }  
});
```
And I get something really ugly like this 

<img width="623" alt="Screen Shot 2021-03-27 at 18 04 12" src="https://user-images.githubusercontent.com/12760310/112728309-dcbf8400-8f26-11eb-8a52-925b3d865e63.png">

Unfortunately it is not really clear for me how can I change the text color according to the "value" of the tooltip. The geojson component has a `colorProp` parameter that acts on the scatter so I thought I could use that one also for the text but it seems that it has no effect. Do I really need to define my own function that does the mapping between values - colormap and then set manually the text color in the style? 

Anyway I think these are questions more for the leaflet folks so I will annoy them and leave you alone :) 

But before going I did notice something weird. 
If I start my application using the namespace defined in the `assets` folder with the embedded server (`python app.py`) then everything works fine. However, if I start the app with `gunicorn app:server` then I get the following error in the console

`no match for [myNamespace.mySubNamespace.pointToLayer] in the global window object`

Any idea what could be the problem?

**Comment by guidocioni** [comment]
Sorry, I finally understood how the all things work, especially after I found out where the default namespaces for the scatter are defined here https://github.com/thedirtyfew/dash-leaflet/blob/f8823bca5f7afb0fdc99c80d5105485b72d8a8e8/src/lib/express.js#L64-L93

I just adapted this to only have markers colored with the temperature and permanent tooltips for the text part.
Furthermore I adapted the `clusterToLayer` function to show only 1 point per cluster. The two functions now look like something like this 

```javascript 
window.myNamespace = Object.assign({}, window.myNamespace, {
    mySubNamespace: {
        pointToLayer: function(feature, latlng, context){
            label = String(feature.properties.name)
            const {circleOptions, colorProp} = resolve(context.props.hideout, scatterDefaults,
                ["circleOptions", "colorProp"])
            circleOptions.fillColor = getColor(context.props.hideout, feature.properties[colorProp]);
            return new L.CircleMarker(latlng, circleOptions).bindTooltip("" + label, {
                permanent: true,
                direction: "center",
                className: "my-labels"
            }).openTooltip();
        },

        clusterToLayer: function (feature, latlng, index, context) {
            const {circleOptions, colorProp} = resolve(context.props.hideout, scatterDefaults,
                ["circleOptions", "colorProp"])
            // // Set color based on mean value of leaves.
            const leaves = index.getLeaves(feature.properties.cluster_id);
            // Choose just one value to be representative
            leave = leaves[0]
            label = String(leave.properties[colorProp].toFixed(0))        
            circleOptions.fillColor = getColor(context.props.hideout, leave.properties[colorProp]);
            return new L.CircleMarker(latlng, circleOptions).bindTooltip("" + label, {
                permanent: true,
                direction: "center",
                className: "my-labels"
            }).openTooltip();
        }

    },
});
```

I know, it's definitely not clean but it works :) I will optimize it in the future.

**Comment by guidocioni** [comment]
Here is a demo 

https://user-images.githubusercontent.com/12760310/112756346-07701200-8fe5-11eb-9720-ae160b400593.mov

P.S. the problem with namespace loading with gunicorn was due to the fact that I was not using `__name__` when initializing the Dash app :)

**Comment by emilhe** [comment]
That looks nice! Thanks for the demo ;)

**Comment by guidocioni** [comment]
Sorry, last comment. I just figured out that doing with the scatter is much better than binding the tooltips (the UI is much faster). here is the latest version


```javascript
        pointToLayer: function(feature, latlng, context){
            const {circleOptions, colorProp} = resolve(context.props.hideout, scatterDefaults,
                ["circleOptions", "colorProp"])
            label = String(feature.properties[colorProp].toFixed(0))
            const icon = L.divIcon.scatter({
                html: '<div><span>' + label + '</span></div>',
                iconSize: L.point(20, 20),
                className: "marker-modified",
                color: getColor(context.props.hideout, feature.properties[colorProp])
            });
            return L.marker(latlng, {icon : icon})
        },

        clusterToLayer: function (feature, latlng, index, context) {
            const {circleOptions, colorProp} = resolve(context.props.hideout, scatterDefaults,
                ["circleOptions", "colorProp"])
            const leaves = index.getLeaves(feature.properties.cluster_id);
            // Choose just one value to be representative
            leave = leaves[0]
            console.log(leave)
            label = String(leave.properties[colorProp].toFixed(0))
            const icon = L.divIcon.scatter({
                html: '<div><span>' + label + '</span></div>',
                iconSize: L.point(20, 20),
                className: "marker-modified",
                color: getColor(context.props.hideout, leave.properties[colorProp])
            });
            return L.marker(latlng, {icon : icon})
        }
```

Only thing that I still didn't manage to do is to activate the tooltips for the points of the clusters. Right now they appear as normal points but they're not and it appears that Leaflet does not support hover tooltips for superclusters so...I'll have to invest some time to figure it out :)
