### ISSUE TITLE
Dash callback on overlay.checked changed

### ISSUE THREAD

**Issue by Wormfriend** [thedirtyfew/dash-leaflet#87]
Hi,

first of all thank you very much for your amazing work! 
I was wondering if it is possible to change the checked status of an overlay within a LayersControl programmatically from within a callback?

Thank you already for your answer. :)

**Comment by Wormfriend** [comment]
It might be, that I am missing a key concept of react or dash, but I am new to dash and also not really quite firm with react so I might be looking for the wrong keywords after all. A little help or something to look/read into would be really lovely. :) Enjoy your evening  - at least here it's quite late already already.

**Comment by emilhe** [comment]
Thanks! The reason you cannot find it is because I haven't implemented any way to do it. Feel free to make a pull request. Hence at the moment, the only thing this behavior can be achieved is by updating the content of the overlay control itself,

```
import uuid
import dash_html_components as html
import dash_leaflet as dl
from dash import Dash
from dash.dependencies import Output, Input

def tile_layers(check):
    keys = ["watercolor", "toner", "terrain"]
    url_template = "http://{{s}}.tile.stamen.com/{}/{{z}}/{{x}}/{{y}}.png"
    return [dl.BaseLayer(dl.TileLayer(id=str(uuid.uuid4()),  # assign unique id to force update
                                      url=url_template.format(key)), name=key, checked=key == check) for key in keys]

# Create app.
app = Dash()
app.layout = html.Div([
    dl.Map(dl.LayersControl(tile_layers(check="toner"), id="layers"), zoom=7, center=(56, 10),
           style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block"}),
    html.Button("Terrain", id="terrain")
])

@app.callback(Output("layers", "children"), [Input("terrain", "n_clicks")], prevent_initial_call=True)
def update(_):
    return tile_layers("terrain")

if __name__ == '__main__':
    app.run_server(port=5757, debug=True)
```
In general, I would prefer questions on SO and bug here git GitHub. Have a good evening :)

**Comment by Wormfriend** [comment]
Hey, 
thank you very much for your response! 
I am relatively new to contributing in open source software - thank's to corona I at least got started at some point. I just wasn't sure where to ask, but thank you anyway. Next time I'll ask on SO. :)
