### ISSUE TITLE
cannot use dash-leaflet with django-plotly-dash

### ISSUE THREAD

**Issue by kirodh** [thedirtyfew/dash-leaflet#88]
Hi there

I am trying to use dash_leaflet with django via django_plotly_dash. It does not seem to render the map. Is it possible you could look into this please?

`
import dash
import dash_leaflet as dl
from django_plotly_dash import DjangoDash
import dash_html_components as html

url = 'https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png'
attribution = '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a> '

app = DjangoDash('dash_integration_id')

app.layout = html.Div([html.Div("hi there",style={"zIndex":1}),
    dl.Map(dl.TileLayer(url=url, maxZoom=20, attribution=attribution))
], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block", "position": "relative","zIndex":100})

if __name__ == '__main__':
    app.run_server(debug=True)
`
The hi there appears when the dl.Map is commented out. But nothing appears when uncommented.

Thanks

**Comment by emilhe** [comment]
I believe you are correct that dash-leaflet is not compatible with `DjangoDash`. I vaguely remember this have been reported before. I haven't used `DjangoDash` myself, so I can't comment on the combability. But I am always happy to look at a pull request :)

**Comment by kirodh** [comment]
Hi emilhe

I managed to get it to work. You need to add dash_leaflet as a plotly app. Then everything works like a charm :-)

Thanks!

**Comment by vedranmarkulj** [comment]
> Hi emilhe
> 
> I managed to get it to work. You need to add dash_leaflet as a plotly app. Then everything works like a charm :-)
> 
> I did notice that the Easy button breaks the map while using django_dash.
> 
> Thanks!

Hi kirodh,

Can you please expand a little more on your explanation? What do you mean by "add dash_leaflet as a plotly app". I am fairly new to Django and dash so it might be very basic.

**Comment by kirodh** [comment]
> 
> 
> > Hi emilhe
> > I managed to get it to work. You need to add dash_leaflet as a plotly app. Then everything works like a charm :-)
> > I did notice that the Easy button breaks the map while using django_dash.
> > Thanks!
> 
> Hi kirodh,
> 
> Can you please expand a little more on your explanation? What do you mean by "add dash_leaflet as a plotly app". I am fairly new to Django and dash so it might be very basic.

Hey

Try following this tutorial:

https://thinkinfi.com/integrate-plotly-dash-in-django/


It works, except the line 'channels', in the INSTALLED_APPS variable in your settings.py file. Comment or delete that 'channels',.

Later on in your settings.py file you have the following variable:
```
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_bootstrap_components',
    'dash_renderer',
    'dpd_components',
    'dpd_static_support',
]

```
All you do is insert 'dash_leaflet' into this variable like so:

```
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_bootstrap_components',
    'dash_renderer',
    'dpd_components',
    'dpd_static_support',
    'dash_leaflet',
]

```


and you should be sorted.

**Comment by smailt** [comment]
I have the same problem it shows me a blank plot.
I tried the solution above.

Have you solved this issue?

**Comment by emilhe** [comment]
I haven't made any effort to address it. I am not using Django myself, so it isn't high on the priority list.

**Comment by baerr** [comment]
I would be very interested in a solution as well. My map is no rendering either using Django and dash…

**Comment by kirodh** [comment]
Hey

Apart from the above for removing the channels from installed apps and the 

Here are the versions of python packages used in my django project (note some packages will probs not be needed for you proj):
django-extensions==2.2.9
django-organizations==1.1.2
django-countries==6.1.2
django-phonenumber-field==4.0.0
django-crispy-forms==1.11.2
django-leaflet==0.28.0
django_plotly_dash==1.6.4
django-geojson==3.2.0
channels==3.0.3
bootstrap4==0.1.0
dpd_static_support==0.0.5
dash
dash_daq==0.5.0
dash_bootstrap_components==0.12.2
dash-leaflet==0.1.14rc3
dash-extensions==0.0.64
whitenoise==5.2.0

Other stuff that may help you:
- Not sure if it will work for dash v2+, I was using version 1.x.x
- make sure you have your routing.py file in your main app
- load your tags in the html file, looks something like this: {% load plotly_dash%}
- add the actual plot in the html, looks something like this: 
    {% plotly_app name="dash_integration_id" ratio=1.0 %}
- ensure that the id above is the same as your dash app code file where you define you app: app = DjangoDash('dash_integration_id', external_stylesheets=[dbc.themes.CERULEAN])

hope this helps

**Comment by seb5g** [comment]
I'm having the same issue with newer version of the involved packages. 
When just using Dash and DashLeaflet everything is fine. But then when loading it using DjangoDash then the map is not rendering. Here are a few things I've noticed:

- DjangoDash loads the maps into an iframe
- when inspecting the browser, many errors appears which I suppose are the origins of the issue:

_The error is: The ressource at adress « https://unpkg.com/dash_leaflet@0.1.23/dash_leaflet/dash_leaflet.min.js » has been bloqued because of an incorrect MIME type (« text/plain »)  (X-Content-Type-Options: nosniff)._

Any idea what to look for to solve this?
