### ISSUE TITLE
Choropleth

### ISSUE THREAD

**Issue by hovhannisyan91** [thedirtyfew/dash-leaflet#9]
Hello, thanks for the package

I am a  Data Scientist, trying to build dash app. Is there a way to add choropleth.

I want to recreate https://leafletjs.com/examples/choropleth/ with dash components.

**Comment by emilhe** [comment]
Hello,

With the current version, you could make a Choropleth visualization using the polygon element. I plan to enable geojson overlays in the near future, at that point you would be able to do something similar to the example in you link.

\emher

**Comment by emilhe** [comment]
Could you elaborate on which particular features that you are interested in? I am currently writing a GeoJSON component, so it might be worth considering your usecase in the process.

**Comment by hovhannisyan91** [comment]
Thanks for your contributions man!

I was trying to create web app, for geoanalytics. 
The main featuer of maps are, creating choropleth maps given values which can be selected from drobdown. There is three main filters, which should by dynamic-
Region(dropdown), values(dropdown:) and daterangepicker.

**Comment by emilhe** [comment]
So if i understand you correctly,

* Region change would change the whole geometry, i.e. a new GeoJSON must be sent to the client
* Value or date change would change only the color of each element, i.e. ideally it should be possible to update the colors without sending the GeoJSON file again?

\emher

**Comment by emilhe** [comment]
I have added a GeoJSON component (from version 0.0.11), which enables Choropleth visualizations.
