### ISSUE TITLE
Zoom to polygon bounds -- alternative to click

### ISSUE THREAD

**Issue by prl900** [thedirtyfew/dash-leaflet#93]
I'm seeking some help with adding the "zoom to bounds" functionality, that is currently available when a polygon is clicked, to other ways of selecting polygons -- for example using a dropdown list. 

The use case is similar to the "Choropleth map" example adding a dropdown list for selecting US states. I would like to know if zooming into the bounds of the state can be achieved in the same way as if the state was clicked on the map.

The Cloropleth example shows a few options that might help to achieve this:
```
geojson = dl.GeoJSON(url="/assets/us-states.json",  # url to geojson file
                     options=dict(style=ns("style")),  # how to style each polygon
                     zoomToBounds=True,  # when true, zooms to bounds when data changes (e.g. on load)
                     zoomToBoundsOnClick=True,  # when true, zooms to bounds of feature (e.g. polygon) on click
                     hoverStyle=arrow_function(dict(weight=5, color='#666', dashArray='')),  # style applied on hover
                     hideout=dict(colorscale=colorscale, classes=classes, style=style, colorProp="density"),
                     id="geojson")
```

The `zoomToBoundsOnClick` seems to be responsible for enabling the mouse click but I wonder if anyone knows how to use the `zoomToBounds` option and if it can be used for selecting polygons dynamically after the layer has been loaded.

I guess a straightforward way of achieving this behavior would be to modify the `center` and `zoom` parameters of the `Map` object in a callback, but working out the center and zoom level values to fit polygons of any shape and size is non-trivial. Other alternatives or ideas to achieve this would be greatly appreciated. 

Thank you very much for your help

**Comment by emilhe** [comment]
One option could be to draw a transparent GeoJSON layer below the real one, apply filtering to it as per your drop down selection and then set zoomToBounds=True.

**Comment by prl900** [comment]
Thanks for the suggestion @emilhe. If I understand correctly, you are suggesting something like this:

```
data = json.loads(geojson_data)
geojson = dl.GeoJSON(id="geojson",
                     data=data,
                     zoomToBounds=True,  # when true, zooms to bounds when data changes
                 )
```
And then changing the contents of the data variable dynamically. 

I have tried this approach but I don't manage to make the zoom change when the variable gets updated. It's also tricky in my case with having to modify a global variable, which seems to go against the Dash recommendation of using them. I wonder if you know about some sample code that does something similar.

Thanks!

**Comment by emilhe** [comment]
@prl900 That should work too, but I would recommend doing the filtering clientside via the built-in functionality of the GeoJSON component, as that would be much performant.

**Comment by emilhe** [comment]
@prl900 I have just pushed the new dash leaflet documentation. It includes an example in how to do client side filtering,

https://dash-leaflet.herokuapp.com/#geojson_hideout
