### ISSUE TITLE
geojson_hideout example doesn't work with debugger on

### ISSUE THREAD

**Issue by heidler** [thedirtyfew/dash-leaflet#99]
Hey guys, when I copy & paste and [run example](https://dash-leaflet.herokuapp.com/#geojson_hideout) from doc site and enable debugger:

```
if __name__ == '__main__':
    app.run_server(debug = True)
```

I've got this error:
<img width="960" alt="msedge_dFdeZAzius" src="https://user-images.githubusercontent.com/8638578/125176964-53cc1000-e1d8-11eb-9f14-fbc537706093.png">

Any ideas how to fix it?

Thanks

**Comment by emilhe** [comment]
It looks like the type validation is a bit too strict. I’ll relax it in the next update. For now, you can ignore it - or wrap the array in a dict

\emher 

Sendt fra min iPhone
